#!/usr/bin/env python3
"""
realdata_dual_validation_colab.py
=================================
Self-contained Google Colab script for real data validation.

USAGE:
  1. Upload `real_data_preprocessed.npz` (generated by export_real_data.py)
  2. Run this entire script on Colab GPU
  3. Download charts + CSV from /content/realdata_results/

Runs the best PLS + top-5 CNN configs from the ideal grid search on REAL
experimental data with repeated cross-validation.
"""

import os, time
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import KFold
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import warnings
warnings.filterwarnings("ignore")

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

np.random.seed(42)
torch.manual_seed(42)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

if torch.cuda.is_available():
    print(f"  Using device: {DEVICE}")
    print(f"  GPU: {torch.cuda.get_device_name(0)}")
    print(f"  VRAM: {torch.cuda.get_device_properties(0).total_mem / 1e9:.1f} GB")
else:
    print("  ⚠ No GPU detected! Running on CPU (will be slower).")

# ─────────────────────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────────────────────
# Try Colab upload, then local path
NPZ_PATH = None
for p in ["real_data_preprocessed.npz", "/content/real_data_preprocessed.npz"]:
    if os.path.exists(p):
        NPZ_PATH = p
        break

if NPZ_PATH is None:
    try:
        from google.colab import files
        print("\n📂 Please upload real_data_preprocessed.npz:")
        uploaded = files.upload()
        NPZ_PATH = list(uploaded.keys())[0]
    except ImportError:
        raise FileNotFoundError(
            "real_data_preprocessed.npz not found. "
            "Run export_real_data.py locally first, then upload here."
        )

data = np.load(NPZ_PATH)
X = data["X"]
Y = data["Y"]
print(f"\n  Loaded: X={X.shape}, Y={Y.shape}")
print(f"  Chl-a range: {Y[:, 0].min():.2f}–{Y[:, 0].max():.2f} mg/L")
print(f"  Chl-b range: {Y[:, 1].min():.2f}–{Y[:, 1].max():.2f} mg/L")

OUT_DIR = "/content/realdata_results" if os.path.exists("/content") else "realdata_results"
os.makedirs(OUT_DIR, exist_ok=True)

# ─────────────────────────────────────────────────────────────
# GRID SEARCH WINNERS (from Colab ideal-data run)
# ─────────────────────────────────────────────────────────────
BEST_PLS = {"n_components": 15, "label": "PLS (n=15)"}

TOP_CNN_CONFIGS = [
    {"kernels": (51,25,11), "filters": (16,32,64), "lr": 3e-3, "epochs": 80,
     "batch_size": 16, "dropout_conv": 0.1, "dropout_fc": 0.2,
     "label": "CNN #1: k(51,25,11) lr=3e-3"},
    {"kernels": (31,15,7), "filters": (16,32,64), "lr": 3e-3, "epochs": 120,
     "batch_size": 16, "dropout_conv": 0.1, "dropout_fc": 0.2,
     "label": "CNN #2: k(31,15,7) ep120"},
    {"kernels": (31,15,7), "filters": (16,32,64), "lr": 3e-3, "epochs": 80,
     "batch_size": 16, "dropout_conv": 0.1, "dropout_fc": 0.2,
     "label": "CNN #3: k(31,15,7) ep80"},
    {"kernels": (41,21,11), "filters": (32,64,128), "lr": 1e-3, "epochs": 120,
     "batch_size": 16, "dropout_conv": 0.1, "dropout_fc": 0.2,
     "label": "CNN #4: k(41,21,11) f(32,64,128)"},
    {"kernels": (21,11,5), "filters": (32,64,128), "lr": 1e-3, "epochs": 120,
     "batch_size": 16, "dropout_conv": 0.2, "dropout_fc": 0.2,
     "label": "CNN #5: k(21,11,5) f(32,64,128)"},
]


# ─────────────────────────────────────────────────────────────
# PLS EVALUATION
# ─────────────────────────────────────────────────────────────
def evaluate_pls_repeated(X, Y, n_components, n_repeats=3, n_splits=20):
    all_preds = np.zeros((n_repeats, len(Y), 2))
    for rep in range(n_repeats):
        kf = KFold(n_splits=n_splits, shuffle=True, random_state=42 + rep)
        fold_preds = np.zeros_like(Y)
        for train_idx, test_idx in kf.split(X):
            m = PLSRegression(n_components=n_components)
            m.fit(X[train_idx], Y[train_idx])
            fold_preds[test_idx] = m.predict(X[test_idx])
        all_preds[rep] = fold_preds

    mean_preds = all_preds.mean(axis=0)
    std_preds  = all_preds.std(axis=0)
    metrics = {}
    for key, col in [("a", 0), ("b", 1)]:
        metrics[f"r2_{key}"]   = [r2_score(Y[:, col], all_preds[r, :, col]) for r in range(n_repeats)]
        metrics[f"rmse_{key}"] = [np.sqrt(mean_squared_error(Y[:, col], all_preds[r, :, col])) for r in range(n_repeats)]
        metrics[f"mae_{key}"]  = [mean_absolute_error(Y[:, col], all_preds[r, :, col]) for r in range(n_repeats)]
    return mean_preds, std_preds, metrics


# ─────────────────────────────────────────────────────────────
# CNN
# ─────────────────────────────────────────────────────────────
class DualCNN1D(nn.Module):
    def __init__(self, input_len, kernel_sizes=(51,25,11), filters=(16,32,64),
                 dropout_conv=0.1, dropout_fc=0.2):
        super().__init__()
        k1, k2, k3 = kernel_sizes
        f1, f2, f3 = filters
        self.features = nn.Sequential(
            nn.Conv1d(1, f1, kernel_size=k1, padding=k1//2),
            nn.BatchNorm1d(f1), nn.ReLU(), nn.MaxPool1d(4),
            nn.Dropout(dropout_conv),
            nn.Conv1d(f1, f2, kernel_size=k2, padding=k2//2),
            nn.BatchNorm1d(f2), nn.ReLU(), nn.MaxPool1d(4),
            nn.Dropout(dropout_conv),
            nn.Conv1d(f2, f3, kernel_size=k3, padding=k3//2),
            nn.BatchNorm1d(f3), nn.ReLU(),
            nn.AdaptiveAvgPool1d(8),
        )
        self.regressor = nn.Sequential(
            nn.Flatten(),
            nn.Linear(f3 * 8, 128), nn.ReLU(), nn.Dropout(dropout_fc),
            nn.Linear(128, 32), nn.ReLU(),
            nn.Linear(32, 2),
        )

    def forward(self, x):
        return self.regressor(self.features(x))


def train_cnn_fold(X_tr, Y_tr, X_te, config):
    model = DualCNN1D(
        X_tr.shape[1],
        kernel_sizes=config["kernels"], filters=config["filters"],
        dropout_conv=config["dropout_conv"], dropout_fc=config["dropout_fc"],
    ).to(DEVICE)

    opt = torch.optim.Adam(model.parameters(), lr=config["lr"], weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=config["epochs"])
    loss_fn = nn.MSELoss()

    Xt = torch.FloatTensor(X_tr).unsqueeze(1).to(DEVICE)
    Yt = torch.FloatTensor(Y_tr).to(DEVICE)
    ds = TensorDataset(Xt, Yt)
    dl = DataLoader(ds, batch_size=config["batch_size"], shuffle=True)

    model.train()
    for _ in range(config["epochs"]):
        for xb, yb in dl:
            opt.zero_grad()
            loss_fn(model(xb), yb).backward()
            opt.step()
        scheduler.step()

    model.eval()
    with torch.no_grad():
        preds = model(torch.FloatTensor(X_te).unsqueeze(1).to(DEVICE)).cpu().numpy()
    return preds


def evaluate_cnn_repeated(X, Y, config, n_repeats=3, n_splits=5):
    all_preds = np.zeros((n_repeats, len(Y), 2))
    for rep in range(n_repeats):
        kf = KFold(n_splits=n_splits, shuffle=True, random_state=42 + rep)
        fold_preds = np.zeros_like(Y)
        for fold, (tr, te) in enumerate(kf.split(X)):
            fold_preds[te] = train_cnn_fold(X[tr], Y[tr], X[te], config)
        all_preds[rep] = fold_preds
        r2a = r2_score(Y[:, 0], fold_preds[:, 0])
        r2b = r2_score(Y[:, 1], fold_preds[:, 1])
        print(f"    Rep {rep+1}/{n_repeats}  R²_a={r2a:.4f}  R²_b={r2b:.4f}")

    mean_preds = all_preds.mean(axis=0)
    std_preds  = all_preds.std(axis=0)
    metrics = {}
    for key, col in [("a", 0), ("b", 1)]:
        metrics[f"r2_{key}"]   = [r2_score(Y[:, col], all_preds[r, :, col]) for r in range(n_repeats)]
        metrics[f"rmse_{key}"] = [np.sqrt(mean_squared_error(Y[:, col], all_preds[r, :, col])) for r in range(n_repeats)]
        metrics[f"mae_{key}"]  = [mean_absolute_error(Y[:, col], all_preds[r, :, col]) for r in range(n_repeats)]
    return mean_preds, std_preds, metrics


# ═════════════════════════════════════════════════════════════
# CHARTS
# ═════════════════════════════════════════════════════════════
def plot_all_results(results_list, Y, out_path):
    """Single multi-panel figure: one row per model, Chl-a (left) + Chl-b (right)."""
    n = len(results_list)
    fig, axes = plt.subplots(n, 2, figsize=(14, 4.2 * n))
    if n == 1:
        axes = axes.reshape(1, -1)

    for row, res in enumerate(results_list):
        label  = res["label"]
        mean_p = res["mean_preds"]
        std_p  = res["std_preds"]
        met    = res["metrics"]
        color  = res.get("color", "royalblue")

        for col, (name, key) in enumerate([("Chl-a", "a"), ("Chl-b", "b")]):
            ax = axes[row, col]
            yt = Y[:, col]
            yp = mean_p[:, col]
            ys = std_p[:, col]

            r2   = np.mean(met[f"r2_{key}"])
            rmse = np.mean(met[f"rmse_{key}"])
            mae  = np.mean(met[f"mae_{key}"])
            r2_ci   = [np.min(met[f"r2_{key}"]),   np.max(met[f"r2_{key}"])]
            rmse_ci = [np.min(met[f"rmse_{key}"]), np.max(met[f"rmse_{key}"])]
            mae_ci  = [np.min(met[f"mae_{key}"]),  np.max(met[f"mae_{key}"])]

            lmin = min(yt.min(), yp.min()) * 0.85
            lmax = max(yt.max(), yp.max()) * 1.08
            ax.plot([lmin, lmax], [lmin, lmax], 'k--', lw=1, alpha=0.5)
            ax.errorbar(yt, yp, yerr=ys, fmt='o', color=color,
                        mfc=color, mec='k', ms=5, alpha=0.7, capsize=2,
                        elinewidth=0.8)

            box = (f"R²   = {r2:.3f} [{r2_ci[0]:.3f}, {r2_ci[1]:.3f}]\n"
                   f"RMSE = {rmse:.3f} [{rmse_ci[0]:.3f}, {rmse_ci[1]:.3f}]\n"
                   f"MAE  = {mae:.3f} [{mae_ci[0]:.3f}, {mae_ci[1]:.3f}]")
            ax.text(0.03, 0.97, box, transform=ax.transAxes, fontsize=8,
                    va='top', fontfamily='monospace',
                    bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.85))

            ax.set_xlim(lmin, lmax); ax.set_ylim(lmin, lmax)
            ax.set_xlabel(f"Actual [{name}] mg/L", fontsize=9)
            ax.set_ylabel(f"Predicted [{name}] mg/L", fontsize=9)
            ax.set_title(f"{label} — {name}", fontsize=10, fontweight='bold')
            ax.grid(True, alpha=0.2)
            ax.set_aspect('equal', adjustable='box')

    fig.suptitle("Real Data Validation: PLS vs Top-5 CNN Configs\n"
                 "(Grid-search-optimised on ideal simulation → tested on real experimental data)",
                 fontsize=13, fontweight='bold', y=1.01)
    plt.tight_layout()
    fig.savefig(out_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"\n  ✅ Combined chart saved: {out_path}")


def plot_summary_bars(summary_df, out_path):
    """Horizontal bar chart comparing all models."""
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    df = summary_df.sort_values("total_rmse")
    labels = df["model"].values
    colors = ['#2196F3' if 'PLS' in l else '#FF9800' for l in labels]

    for ax, metric, title in zip(axes,
            ["total_rmse", "mean_r2_a", "mean_r2_b"],
            ["Total RMSE (↓ better)", "Mean R² Chl-a (↑ better)", "Mean R² Chl-b (↑ better)"]):
        bars = ax.barh(range(len(df)), df[metric], color=colors, edgecolor='k', lw=0.5)
        ax.set_yticks(range(len(df)))
        ax.set_yticklabels(labels, fontsize=8)
        ax.set_xlabel(metric.replace("_", " ").title(), fontsize=10)
        ax.set_title(title, fontsize=11, fontweight='bold')
        for bar, val in zip(bars, df[metric]):
            ax.text(bar.get_width() + 0.01, bar.get_y() + bar.get_height()/2,
                    f"{val:.3f}", va='center', fontsize=8)
        ax.grid(True, axis='x', alpha=0.3)
    plt.tight_layout()
    fig.savefig(out_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"  ✅ Summary bars saved: {out_path}")


# ═════════════════════════════════════════════════════════════
# MAIN
# ═════════════════════════════════════════════════════════════
print("=" * 70)
print("  REAL DATA VALIDATION — Grid-Search-Optimised Models")
print(f"  Device: {DEVICE}")
print("=" * 70)

results_list = []
summary_rows = []

# ── PLS ──────────────────────────────────────────────────────
print(f"\n[1/6] PLS (n_components={BEST_PLS['n_components']})...")
t0 = time.time()
pls_mean, pls_std, pls_met = evaluate_pls_repeated(X, Y, BEST_PLS["n_components"])
pls_t = time.time() - t0

r2a, r2b = np.mean(pls_met["r2_a"]), np.mean(pls_met["r2_b"])
rmsea, rmseb = np.mean(pls_met["rmse_a"]), np.mean(pls_met["rmse_b"])
maea, maeb = np.mean(pls_met["mae_a"]), np.mean(pls_met["mae_b"])
print(f"  Chl-a R²={r2a:.4f} RMSE={rmsea:.3f}  |  Chl-b R²={r2b:.4f} RMSE={rmseb:.3f}  [{pls_t:.1f}s]")

results_list.append({"label": BEST_PLS["label"], "mean_preds": pls_mean,
                      "std_preds": pls_std, "metrics": pls_met, "color": "#2196F3"})
summary_rows.append({"model": BEST_PLS["label"], "mean_r2_a": r2a, "mean_r2_b": r2b,
                      "mean_rmse_a": rmsea, "mean_rmse_b": rmseb,
                      "mean_mae_a": maea, "mean_mae_b": maeb,
                      "total_rmse": rmsea + rmseb, "time_s": pls_t})

# ── Top-5 CNN ────────────────────────────────────────────────
cnn_colors = ["#FF9800", "#E91E63", "#4CAF50", "#9C27B0", "#795548"]

for i, config in enumerate(TOP_CNN_CONFIGS):
    print(f"\n[{i+2}/6] {config['label']}...")
    t0 = time.time()
    cnn_mean, cnn_std, cnn_met = evaluate_cnn_repeated(X, Y, config, n_repeats=3, n_splits=5)
    cnn_t = time.time() - t0

    r2a, r2b = np.mean(cnn_met["r2_a"]), np.mean(cnn_met["r2_b"])
    rmsea, rmseb = np.mean(cnn_met["rmse_a"]), np.mean(cnn_met["rmse_b"])
    maea, maeb = np.mean(cnn_met["mae_a"]), np.mean(cnn_met["mae_b"])
    print(f"  Chl-a R²={r2a:.4f} RMSE={rmsea:.3f}  |  Chl-b R²={r2b:.4f} RMSE={rmseb:.3f}  [{cnn_t:.1f}s]")

    results_list.append({"label": config["label"], "mean_preds": cnn_mean,
                          "std_preds": cnn_std, "metrics": cnn_met, "color": cnn_colors[i]})
    summary_rows.append({"model": config["label"], "mean_r2_a": r2a, "mean_r2_b": r2b,
                          "mean_rmse_a": rmsea, "mean_rmse_b": rmseb,
                          "mean_mae_a": maea, "mean_mae_b": maeb,
                          "total_rmse": rmsea + rmseb, "time_s": cnn_t})

# ── Charts ───────────────────────────────────────────────────
print("\n  Generating charts...")
chart_path = f"{OUT_DIR}/realdata_dual_validation_all.png"
plot_all_results(results_list, Y, chart_path)

summary_df = pd.DataFrame(summary_rows)
bars_path = f"{OUT_DIR}/realdata_dual_summary_bars.png"
plot_summary_bars(summary_df, bars_path)

csv_path = f"{OUT_DIR}/realdata_dual_summary.csv"
summary_df.to_csv(csv_path, index=False)
print(f"  ✅ Summary CSV: {csv_path}")

# ── Final Table ──────────────────────────────────────────────
print("\n" + "=" * 70)
print("  REAL DATA VALIDATION — FINAL RESULTS")
print("=" * 70)
summary_df = summary_df.sort_values("total_rmse")
print(f"\n  {'Model':<38}  {'R²_a':>6}  {'R²_b':>6}  {'RMSE_a':>7}  {'RMSE_b':>7}  {'ΣRMSE':>7}  {'Time':>6}")
print(f"  {'-'*85}")
for _, r in summary_df.iterrows():
    marker = " 🏆" if _ == summary_df.index[0] else ""
    print(f"  {r['model']:<38}  {r['mean_r2_a']:>6.4f}  {r['mean_r2_b']:>6.4f}  "
          f"{r['mean_rmse_a']:>7.3f}  {r['mean_rmse_b']:>7.3f}  "
          f"{r['total_rmse']:>7.3f}  {r['time_s']:>5.1f}s{marker}")

winner = summary_df.iloc[0]
print(f"\n  🏆 Winner on real data: {winner['model']}")
print(f"\n  All outputs saved to: {OUT_DIR}/")
