
import numpy as np
import pandas as pd
import joblib
from pathlib import Path
from scipy.signal import savgol_filter
from sklearn.cross_decomposition import PLSRegression
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVR
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

# ============================================================
# CONFIGURATION
# ============================================================
SCRIPT_DIR = Path(__file__).parent.resolve()
DATA_DIR_A = SCRIPT_DIR / "chla2"
DATA_DIR_B = SCRIPT_DIR / "chlb2"
BACKGROUND_DIR = SCRIPT_DIR.parent / "background_data"

EXCEL_A = SCRIPT_DIR / "chladata.xlsx"
EXCEL_B = SCRIPT_DIR / "chlb.xlsx"

OUTPUT_MODEL_A = SCRIPT_DIR / "chla_model.pkl"
OUTPUT_MODEL_B = SCRIPT_DIR / "chlb_model.pkl"

# Constants
PLS_N_COMPONENTS_A = 9
PCA_VARIANCE_B = 0.98
SVR_C_B = 10
SVR_EPSILON_B = 0.01

ROI_START = 1300
ROI_END = 3200

# Background Maps
BACKGROUND_MAP_A = {
    240: "background-240.csv",
    250: "background-250.csv",
    300: "background-300.csv",
    500: "background-500.csv",
    1000: "background-1000.csv",
}
CLOSEST_BG_A = {580: 500, 700: 500}

BACKGROUND_MAP_B = {
    1000: "background-1000.csv",
    1200: "background-1200.csv",
    1500: "background-1500.csv",
    3000: "background-3000.csv",
    5000: "background-5000.csv",
}

# ============================================================
# HELPER FUNCTIONS
# ============================================================

def load_spectrum(path):
    df = pd.read_csv(path)
    # Assume 1st col is index, rest are data. Or usually "0", "1"...
    # Based on existing code: df.iloc[:, 1:]
    # Check if header exists or not? Existing code: pd.read_csv(csv_path), df.iloc[:, 1:]
    # Assuming standard format generated by monitor
    data = df.iloc[:, 1:].values.astype(float)
    return np.mean(data, axis=0)

def load_bg(int_time, bg_map, closest_map, bg_dir):
    time_key = closest_map.get(int_time, int_time)
    fname = bg_map.get(time_key)
    if not fname: return None
    path = bg_dir / fname
    if not path.exists(): return None
    return load_spectrum(path)

def preprocess(spectrum):
    # Savitzky-Golay Smooth
    smoothed = savgol_filter(spectrum, window_length=11, polyorder=2)
    # First Deriv
    deriv = savgol_filter(smoothed, window_length=11, polyorder=3, deriv=1)
    # SNV
    mean = np.mean(deriv)
    std = np.std(deriv)
    snv = (deriv - mean) / (std + 1e-8)
    return snv

def crop(spectrum):
    return spectrum[ROI_START:ROI_END]

def build_dataset(excel_path, data_dir, bg_map, closest_map):
    df = pd.read_excel(excel_path, header=None, skiprows=2)
    df.columns = ["sample", "concentration", "integration_time"]
    df["sample_num"] = df["sample"].str.extract(r"(\d+)").astype(int)
    df["concentration"] = pd.to_numeric(df["concentration"], errors="coerce")
    df["integration_time"] = pd.to_numeric(df["integration_time"], errors="coerce")
    df = df.dropna(subset=["concentration", "integration_time"])
    
    X = []
    y = []
    bg_cache = {}
    
    for _, row in df.iterrows():
        s_num = int(row["sample_num"])
        conc = row["concentration"]
        it = int(row["integration_time"])
        
        fpath = data_dir / f"{s_num}.csv"
        if not fpath.exists(): continue
        
        spec = load_spectrum(fpath)
        
        if it not in bg_cache:
            bg_cache[it] = load_bg(it, bg_map, closest_map, BACKGROUND_DIR)
        
        bg = bg_cache[it]
        if bg is not None:
            min_len = min(len(spec), len(bg))
            spec = spec[:min_len] - bg[:min_len]
            
        # Normalization
        spec = spec / (it + 1e-8)
        
        processed = preprocess(spec)
        cropped = crop(processed)
        
        X.append(cropped)
        y.append(conc)
        
    # Handle lengths
    if not X: return np.array([]), np.array([])
    min_len = min(len(x) for x in X)
    X = np.array([x[:min_len] for x in X])
    y = np.array(y)
    return X, y


# ============================================================
# MAIN TRAINING
# ============================================================
def train_and_save():
    print("Training Chl A Model...")
    # 1. Base Data
    Xa, ya = build_dataset(EXCEL_A, DATA_DIR_A, BACKGROUND_MAP_A, CLOSEST_BG_A)
    
    # 2. Append NPZ Data (New Samples)
    npz_path = SCRIPT_DIR.parent / "dataset.npz"
    if npz_path.exists():
        try:
            print(f"Loading new samples from {npz_path}...")
            data = np.load(npz_path, allow_pickle=True)
            # Check if we have valid arrays
            if 'concentrations' in data and 'laser_a_spectra' in data and 'dark_spectra' in data:
                concs = data['concentrations'] # [ChlA, ChlB]
                laser_a = data['laser_a_spectra']
                dark = data['dark_spectra']
                meta = data['metadata']
                
                new_X = []
                new_y = []
                
                for i in range(len(concs)):
                    # Get integration time from metadata if available, else default?
                    # Metadata is a list of dicts
                    it = 1000 # Default
                    if i < len(meta):
                        it = meta[i].get('integration_time', 1000)
                        
                    # Process
                    spec = laser_a[i].astype(float)
                    dk = dark[i].astype(float)
                    net = spec - dk
                    
                    # Normalize
                    norm = net / (it + 1e-8)
                    
                    processed = preprocess(norm)
                    cropped = crop(processed)
                    
                    new_X.append(cropped)
                    new_y.append(concs[i][0]) # Chl A conc
                    
                if new_X:
                    new_X = np.array(new_X)
                    new_y = np.array(new_y)
                    # Append
                    if len(Xa) > 0:
                        Xa = np.vstack([Xa, new_X])
                        ya = np.concatenate([ya, new_y])
                    else:
                        Xa = new_X
                        ya = new_y
                    print(f"  Added {len(new_X)} new samples to Chl A training set.")
        except Exception as e:
            print(f"Failed to load NPZ data: {e}")

    if len(Xa) > 0:
        ma = PLSRegression(n_components=PLS_N_COMPONENTS_A, scale=True)
        ma.fit(Xa, ya)
        joblib.dump(ma, OUTPUT_MODEL_A)
        print(f"Saved Chl A Model to {OUTPUT_MODEL_A}")
    else:
        print("No data for Chl A")

    print("Training Chl B Model...")
    Xb, yb = build_dataset(EXCEL_B, DATA_DIR_B, BACKGROUND_MAP_B, {})
    
    # 2. Append NPZ Data (Chl B)
    if npz_path.exists():
        try:
            data = np.load(npz_path, allow_pickle=True)
            if 'concentrations' in data and 'laser_b_spectra' in data and 'dark_spectra' in data:
                concs = data['concentrations']
                laser_b = data['laser_b_spectra']
                dark = data['dark_spectra']
                meta = data['metadata']
                
                new_X = []
                new_y = []
                
                for i in range(len(concs)):
                    it = 1000
                    if i < len(meta):
                        it = meta[i].get('integration_time', 1000)
                        
                    spec = laser_b[i].astype(float)
                    dk = dark[i].astype(float)
                    net = spec - dk
                    
                    norm = net / (it + 1e-8)
                    processed = preprocess(norm)
                    cropped = crop(processed)
                    
                    new_X.append(cropped)
                    new_y.append(concs[i][1]) # Chl B conc
                    
                if new_X:
                    new_X = np.array(new_X)
                    new_y = np.array(new_y)
                    if len(Xb) > 0:
                        Xb = np.vstack([Xb, new_X])
                        yb = np.concatenate([yb, new_y])
                    else:
                        Xb = new_X
                        yb = new_y
                    print(f"  Added {len(new_X)} new samples to Chl B training set.")
        except:
            pass

    if len(Xb) > 0:
        mb = Pipeline([
            ('scaler', StandardScaler()),
            ('pca', PCA(n_components=PCA_VARIANCE_B)),
            ('svr', SVR(kernel="rbf", C=SVR_C_B, epsilon=SVR_EPSILON_B, gamma='scale'))
        ])
        mb.fit(Xb, yb)
        joblib.dump(mb, OUTPUT_MODEL_B)
        print(f"Saved Chl B Model to {OUTPUT_MODEL_B}")
    else:
        print("No data for Chl B")

