<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Group 04">
<meta name="dcterms.date" content="2026-02-18">

<title>Affordable, Portable, Real-Time Chlorophyll Sensor</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="physics_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="physics_report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="physics_report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="physics_report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="physics_report_files/libs/quarto-html/popper.min.js"></script>
<script src="physics_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="physics_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="physics_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="physics_report_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="physics_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="physics_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="physics_report_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">Executive Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#importance-of-chlorophyll" id="toc-importance-of-chlorophyll" class="nav-link" data-scroll-target="#importance-of-chlorophyll"><span class="header-section-number">1.1</span> Importance of Chlorophyll</a></li>
  <li><a href="#detection-methodology" id="toc-detection-methodology" class="nav-link" data-scroll-target="#detection-methodology"><span class="header-section-number">1.2</span> Detection Methodology</a></li>
  </ul></li>
  <li><a href="#theoretical-framework" id="toc-theoretical-framework" class="nav-link" data-scroll-target="#theoretical-framework"><span class="header-section-number">2</span> Theoretical Framework</a>
  <ul class="collapse">
  <li><a href="#physics-of-laser-induced-fluorescence-lif" id="toc-physics-of-laser-induced-fluorescence-lif" class="nav-link" data-scroll-target="#physics-of-laser-induced-fluorescence-lif"><span class="header-section-number">2.1</span> Physics of Laser-Induced Fluorescence (LIF)</a></li>
  <li><a href="#sec-red-shift" id="toc-sec-red-shift" class="nav-link" data-scroll-target="#sec-red-shift"><span class="header-section-number">2.2</span> Spectral Red Shift &amp; Concentration Features</a></li>
  </ul></li>
  <li><a href="#experimental-setup-hardware" id="toc-experimental-setup-hardware" class="nav-link" data-scroll-target="#experimental-setup-hardware"><span class="header-section-number">3</span> Experimental Setup &amp; Hardware</a>
  <ul class="collapse">
  <li><a href="#system-architecture" id="toc-system-architecture" class="nav-link" data-scroll-target="#system-architecture"><span class="header-section-number">3.1</span> System Architecture</a></li>
  <li><a href="#system-connectivity" id="toc-system-connectivity" class="nav-link" data-scroll-target="#system-connectivity"><span class="header-section-number">3.2</span> System Connectivity</a></li>
  <li><a href="#information-pipeline" id="toc-information-pipeline" class="nav-link" data-scroll-target="#information-pipeline"><span class="header-section-number">3.3</span> Information Pipeline</a></li>
  <li><a href="#circuitry-and-pcb-design" id="toc-circuitry-and-pcb-design" class="nav-link" data-scroll-target="#circuitry-and-pcb-design"><span class="header-section-number">3.4</span> Circuitry and PCB Design</a></li>
  <li><a href="#project-economics-budget" id="toc-project-economics-budget" class="nav-link" data-scroll-target="#project-economics-budget"><span class="header-section-number">3.5</span> Project Economics (Budget)</a></li>
  <li><a href="#sec-data-collection" id="toc-sec-data-collection" class="nav-link" data-scroll-target="#sec-data-collection"><span class="header-section-number">3.6</span> Data Collection Protocol</a></li>
  </ul></li>
  <li><a href="#software-automation" id="toc-software-automation" class="nav-link" data-scroll-target="#software-automation"><span class="header-section-number">4</span> Software &amp; Automation</a>
  <ul class="collapse">
  <li><a href="#firmware-software-design" id="toc-firmware-software-design" class="nav-link" data-scroll-target="#firmware-software-design"><span class="header-section-number">4.1</span> Firmware &amp; Software Design</a></li>
  <li><a href="#automated-operational-logic" id="toc-automated-operational-logic" class="nav-link" data-scroll-target="#automated-operational-logic"><span class="header-section-number">4.2</span> Automated Operational Logic</a></li>
  </ul></li>
  <li><a href="#methodology-signal-processing-ml" id="toc-methodology-signal-processing-ml" class="nav-link" data-scroll-target="#methodology-signal-processing-ml"><span class="header-section-number">5</span> Methodology: Signal Processing &amp; ML</a>
  <ul class="collapse">
  <li><a href="#sec-sample-prep" id="toc-sec-sample-prep" class="nav-link" data-scroll-target="#sec-sample-prep"><span class="header-section-number">5.1</span> Sample Preparation</a></li>
  <li><a href="#digital-signal-processing-pipeline" id="toc-digital-signal-processing-pipeline" class="nav-link" data-scroll-target="#digital-signal-processing-pipeline"><span class="header-section-number">5.2</span> Digital Signal Processing Pipeline</a></li>
  <li><a href="#sec-phase1-models" id="toc-sec-phase1-models" class="nav-link" data-scroll-target="#sec-phase1-models"><span class="header-section-number">5.3</span> Phase 1 Prototype Models</a></li>
  <li><a href="#sec-phase2-model" id="toc-sec-phase2-model" class="nav-link" data-scroll-target="#sec-phase2-model"><span class="header-section-number">5.4</span> Phase 2 — Combined Dual-Analyte Model</a></li>
  <li><a href="#sec-case-study" id="toc-sec-case-study" class="nav-link" data-scroll-target="#sec-case-study"><span class="header-section-number">5.5</span> Case Study: Model Development &amp; Iteration</a></li>
  </ul></li>
  <li><a href="#sec-simulation-study" id="toc-sec-simulation-study" class="nav-link" data-scroll-target="#sec-simulation-study"><span class="header-section-number">6</span> Comprehensive Simulation Study</a>
  <ul class="collapse">
  <li><a href="#effect-of-sample-count-and-peak-alignment" id="toc-effect-of-sample-count-and-peak-alignment" class="nav-link" data-scroll-target="#effect-of-sample-count-and-peak-alignment"><span class="header-section-number">6.1</span> Effect of Sample Count and Peak Alignment</a></li>
  <li><a href="#effect-of-frame-averaging-noise-reduction" id="toc-effect-of-frame-averaging-noise-reduction" class="nav-link" data-scroll-target="#effect-of-frame-averaging-noise-reduction"><span class="header-section-number">6.2</span> Effect of Frame Averaging (Noise Reduction)</a></li>
  <li><a href="#integration-time-optimization" id="toc-integration-time-optimization" class="nav-link" data-scroll-target="#integration-time-optimization"><span class="header-section-number">6.3</span> Integration Time Optimization</a></li>
  <li><a href="#d-cnn-vs-pls-benchmarking" id="toc-d-cnn-vs-pls-benchmarking" class="nav-link" data-scroll-target="#d-cnn-vs-pls-benchmarking"><span class="header-section-number">6.4</span> 1D CNN vs PLS Benchmarking</a></li>
  <li><a href="#recommended-protocol" id="toc-recommended-protocol" class="nav-link" data-scroll-target="#recommended-protocol"><span class="header-section-number">6.5</span> Recommended Protocol</a></li>
  </ul></li>
  <li><a href="#results-discussion" id="toc-results-discussion" class="nav-link" data-scroll-target="#results-discussion"><span class="header-section-number">7</span> Results &amp; Discussion</a>
  <ul class="collapse">
  <li><a href="#experimental-results" id="toc-experimental-results" class="nav-link" data-scroll-target="#experimental-results"><span class="header-section-number">7.1</span> Experimental Results</a></li>
  <li><a href="#uncertainty-model-interpretation" id="toc-uncertainty-model-interpretation" class="nav-link" data-scroll-target="#uncertainty-model-interpretation"><span class="header-section-number">7.2</span> Uncertainty &amp; Model Interpretation</a></li>
  <li><a href="#characterizing-the-signal-integrity-gap" id="toc-characterizing-the-signal-integrity-gap" class="nav-link" data-scroll-target="#characterizing-the-signal-integrity-gap"><span class="header-section-number">7.3</span> Characterizing the Signal Integrity Gap</a></li>
  <li><a href="#sec-current-model" id="toc-sec-current-model" class="nav-link" data-scroll-target="#sec-current-model"><span class="header-section-number">7.4</span> Current Model &amp; Data Assessment</a></li>
  <li><a href="#discussion-of-data-quantity-vs.-algorithm" id="toc-discussion-of-data-quantity-vs.-algorithm" class="nav-link" data-scroll-target="#discussion-of-data-quantity-vs.-algorithm"><span class="header-section-number">7.5</span> Discussion of Data Quantity vs.&nbsp;Algorithm</a></li>
  </ul></li>
  <li><a href="#conclusion-future-outlook" id="toc-conclusion-future-outlook" class="nav-link" data-scroll-target="#conclusion-future-outlook"><span class="header-section-number">8</span> Conclusion &amp; Future Outlook</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">8.1</span> Limitations</a></li>
  <li><a href="#planned-improvements" id="toc-planned-improvements" class="nav-link" data-scroll-target="#planned-improvements"><span class="header-section-number">8.2</span> Planned Improvements</a></li>
  </ul></li>
  <li><a href="#acknowledgements" id="toc-acknowledgements" class="nav-link" data-scroll-target="#acknowledgements">Acknowledgements</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="..\physics_report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Affordable, Portable, Real-Time Chlorophyll Sensor</h1>
<p class="subtitle lead">Physics Report | Group 04</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Group 04 </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Faculty of Science, University of Colombo
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="executive-summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="executive-summary">Executive Summary</h2>
<p>This report details the development of a portable, high-accuracy chlorophyll sensor utilizing <strong>Laser-Induced Fluorescence (LIF)</strong> and <strong>tinyML</strong> algorithms. Designed for agricultural, herbal, and aquatic monitoring, the system provides real-time, calibrated measurements of both Chlorophyll-a (Chl-a) and Chlorophyll-b (Chl-b) concentrations.</p>
</section>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<section id="importance-of-chlorophyll" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="importance-of-chlorophyll"><span class="header-section-number">1.1</span> Importance of Chlorophyll</h3>
<p>Chlorophyll is a primary indicator of plant health, product quality in the herbal industry, and algal biomass in aquatic ecosystems. Monitoring its concentration is critical for water quality assessment and precision agriculture.</p>
</section>
<section id="detection-methodology" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="detection-methodology"><span class="header-section-number">1.2</span> Detection Methodology</h3>
<p>While traditional methods (HPLC, Mass Spectrometry) offer high precision, they are expensive and laboratory-bound. Existing affordable meters often provide only relative content and lack absolute calibration.</p>
<ul>
<li><strong>Research Gap</strong>: Creating an affordable sensor providing calibrated, simultaneous measurements of Chl-a and Chl-b.</li>
<li><strong>Objective</strong>: Prototype a real-time sensor using LIF and on-device edge computing analysis.</li>
</ul>
</section>
</section>
<section id="theoretical-framework" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="theoretical-framework"><span class="header-section-number">2</span> Theoretical Framework</h2>
<section id="physics-of-laser-induced-fluorescence-lif" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="physics-of-laser-induced-fluorescence-lif"><span class="header-section-number">2.1</span> Physics of Laser-Induced Fluorescence (LIF)</h3>
<p>The sensor employs a flow-through system where samples are excited by targeted wavelengths: * <strong>Laser 405 nm</strong>: Optimized for Chl-a excitation. * <strong>Laser 450 nm</strong>: Optimized for Chl-b excitation.</p>
</section>
<section id="sec-red-shift" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="sec-red-shift"><span class="header-section-number">2.2</span> Spectral Red Shift &amp; Concentration Features</h3>
<p>A critical physical observation in this study is the <strong>Red Shift</strong> of the fluorescence peak as concentration increases. This phenomenon occurs due to: * <strong>Inner Filter Effect (IFE)</strong>: Re-absorption of the shorter-wavelength side of the emission spectrum by the chlorophyll matrix. * <strong>Self-Absorption</strong>: The overlap between chlorophyll absorption and emission bands causes selective re-absorption at shorter wavelengths. * <strong>Concentration Quenching</strong>: At high concentrations, molecular aggregation further shifts the emission to longer wavelengths.</p>
<p>These effects produce three measurable spectral features that vary systematically with concentration, as confirmed by our simulation study:</p>
<div id="fig-feature-trends" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-feature-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/feature_trends.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-feature-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Three key spectral features that change with chlorophyll concentration: (a) peak position shifts ~240 pixels across the 0–20 ppm range, (b) intensity saturates following Beer-Lambert law, and (c) FWHM broadens linearly.
</figcaption>
</figure>
</div>
<p>Unlike static peak-height models, our PLS and SVR models analyze the <strong>entire spectral curve</strong>, allowing them to correlate this non-linear shift with absolute concentration. Importantly, our simulation study confirmed that <strong>retaining the red shift</strong> (i.e., not aligning peaks) provides superior model performance compared to peak-aligned spectra.</p>
</section>
</section>
<section id="experimental-setup-hardware" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="experimental-setup-hardware"><span class="header-section-number">3</span> Experimental Setup &amp; Hardware</h2>
<section id="system-architecture" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="system-architecture"><span class="header-section-number">3.1</span> System Architecture</h3>
<ul>
<li><strong>Control Unit</strong>: STM32H743VIT6 (High-performance ARM Cortex-M7 running at 480MHz) for high-speed acquisition and on-device tinyML inference.</li>
<li><strong>Sensor</strong>: Toshiba TCD1304 linear CCD with 3648 active pixels, providing high spatial resolution for fluorescence spectroscopy.</li>
<li><strong>Optical Path</strong>:
<ul>
<li><strong>Excitation</strong>: Dual-laser system (405 nm and 450 nm) targeting the Soret bands of Chl-a and Chl-b, alternately activated via servo-controlled beam positioning.</li>
<li><strong>Dispersion</strong>: 600 lines/mm holographic diffraction grating to resolve the fluorescence emission spectrum.</li>
<li><strong>Collimation</strong>: Cylindrical lens and convex mirror for beam direction; objective lens alignment is performed manually prior to acquisition.</li>
</ul></li>
<li><strong>PCB Design</strong>: A custom PCB was developed using <strong>KiCad</strong> and manufactured via <strong>JLCPCB</strong> to ensure signal integrity and portability.</li>
</ul>
<div id="fig-setup-collage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-setup-collage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/camera/setup-collage.jpeg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-setup-collage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Instrument overview — (left) top-down view of the assembled optical bench, (centre) interior showing the diffraction grating and CCD mount, (right) front panel with cuvette holder and I/O connections.
</figcaption>
</figure>
</div>
</section>
<section id="system-connectivity" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="system-connectivity"><span class="header-section-number">3.2</span> System Connectivity</h3>
<p>The following diagram illustrates the physical and logical connections between the core components:</p>
<div id="fig-sys-connectivity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sys-connectivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/diagrams/system_connectivity.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sys-connectivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: System connectivity diagram showing physical and logical connections between STM32H743VIT6, TCD1304 CCD, lasers, servo, LCD, SD card, and USB
</figcaption>
</figure>
</div>
</section>
<section id="information-pipeline" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="information-pipeline"><span class="header-section-number">3.3</span> Information Pipeline</h3>
<p>The data flow from raw photons to on-device concentration prediction is summarized below:</p>
<div id="fig-firmware-arch" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-firmware-arch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/diagrams/firmware_design.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-firmware-arch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Software architecture class diagram showing the modular firmware design with Core Application, Signal Processing, and Storage packages
</figcaption>
</figure>
</div>
</section>
<section id="circuitry-and-pcb-design" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="circuitry-and-pcb-design"><span class="header-section-number">3.4</span> Circuitry and PCB Design</h3>
<p>The system’s electronic backbone is a custom-designed PCB optimized for low-noise CCD readout and high-speed signal processing.</p>
<div id="fig-schematic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-schematic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/TCD1304_CCD_PCB.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-schematic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: PCB Schematic of the Chlorophyll Sensor System
</figcaption>
</figure>
</div>
<div id="fig-layout" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-layout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/kikad-image.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-layout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: KiCad PCB Layout Implementation
</figcaption>
</figure>
</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-3d-front" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3d-front-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/3d-front.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3d-front-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: PCB 3D Visualization (Front Perspective)
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-3d-back" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3d-back-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/3d-back.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3d-back-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: PCB 3D Visualization (Rear Connectivity)
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div id="fig-pcb-in-use" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pcb-in-use-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/camera/pcb-in-use.jpeg" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pcb-in-use-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: The assembled custom PCB installed inside the instrument chassis, connected to the TCD1304 CCD sensor and laser drivers. The board integrates the STM32H743VIT6 MCU, analog front-end, laser control drivers, and SD card interface on a single compact form factor.
</figcaption>
</figure>
</div>
<section id="key-hardware-features" class="level4" data-number="3.4.1">
<h4 data-number="3.4.1" class="anchored" data-anchor-id="key-hardware-features"><span class="header-section-number">3.4.1</span> Key Hardware Features</h4>
<ul>
<li><strong>MCU High-Speed Interfacing</strong>: The STM32H7 communicates with the TCD1304 CCD using high-speed timers to generate the Master Clock (fM) and Shift Gate (SH) pulses, ensuring synchronized pixel acquisition.</li>
<li><strong>Analog Front-End (AFE)</strong>: To preserve spectral integrity, the CCD’s analog output is buffered and filtered before reaching the STM32’s 16-bit ADC. This minimizes quantization noise and electronic interference.</li>
<li><strong>Laser Control</strong>: Dual constant-current drivers are controlled via high-frequency PWM from the MCU, allowing precise control over excitation intensity and rapid switching between the 405nm and 450nm channels.</li>
<li><strong>Power Management</strong>: A multi-stage voltage regulation system provides stable 3.3V and 5.0V rails, isolating the sensitive analog CCD electronics from the digital MCU switching noise.</li>
</ul>
</section>
</section>
<section id="project-economics-budget" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="project-economics-budget"><span class="header-section-number">3.5</span> Project Economics (Budget)</h3>
<p>The system is designed for maximum affordability without compromising spectral precision. * <strong>Optical Components</strong>: Lasers (405nm, 450nm), diffraction grating, convex mirror, precision slit using two sharp razor blades, and a cylindrical lens. * <strong>Electronics</strong>: STM32H743VIT6 MCU, TCD1304 CCD, 16x2 LCD Module with I2C interface, two 10kΩ potentiometers, two 2N2222 transistors, two 4.7kΩ resistors, two 1kΩ resistors, and one servo motor. * <strong>Manufacturing</strong>: Custom PCB (KiCad/JLCPCB), and a custom 3D-printed cuvette holder. * <strong>Infrastructure</strong>: 3D-printed housing and a flow-through sample chamber.</p>
<div id="fig-solution-series" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-solution-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/camera/solution-series.jpeg" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-solution-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: A dilution series of spinach-extract chlorophyll solutions prepared for calibration. Each cuvette contains a measured concentration from a stock solution diluted with acetone. Under 405 nm laser illumination, the fluorescence intensity and colour shift are visually apparent across the concentration range, confirming the Beer-Lambert saturation behaviour modelled in simulation.
</figcaption>
</figure>
</div>
</section>
<section id="sec-data-collection" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="sec-data-collection"><span class="header-section-number">3.6</span> Data Collection Protocol</h3>
<p>All spectra used for model training were acquired using a custom <strong>Python monitoring application</strong> running on a connected PC over USB serial. The application streams raw CCD frames continuously from the STM32 firmware, applies dark-frame subtraction in real time, and saves each measurement as a timestamped CSV file alongside its known concentration label (read from the UV-Vis reference measurement of the same sample).</p>
<p>The <strong>sample preparation</strong> protocol followed for each acquisition session is as follows:</p>
<ol type="1">
<li><strong>Stock Solution</strong>: Fresh spinach leaves were homogenised in 80% acetone (v/v) and centrifuged at 3000 rpm for 5 minutes to remove cellular debris. The resulting supernatant constitutes the stock solution.</li>
<li><strong>UV-Vis Reference</strong>: Each stock solution was measured in a UV-Vis spectrophotometer using a 10 mm path-length quartz cuvette. Chl-a and Chl-b concentrations were calculated using the Lichtenthaler &amp; Buschmann (2001) simultaneous equations: <span class="math display">\[
[\text{Chl-a}] = 12.21 \cdot A_{663} - 2.81 \cdot A_{646} \quad (\text{mg/L})
\]</span> <span class="math display">\[
[\text{Chl-b}] = 20.13 \cdot A_{646} - 5.03 \cdot A_{663} \quad (\text{mg/L})
\]</span></li>
<li><strong>Serial Dilution</strong>: Starting from the stock, a set of dilutions was prepared volumetrically (1:2, 1:4, 1:8, etc.) using 80% acetone as diluent, covering the concentration range 0.5–20 mg/L.</li>
<li><strong>CCD Acquisition</strong>: Each diluted sample was placed in the 3D-printed flow-through cuvette holder. The auto-exposure algorithm was allowed to converge (typically 3–5 iterations), then <strong>10 consecutive frames</strong> were averaged and saved. Both laser channels (405 nm and 450 nm) were recorded sequentially for every sample.</li>
<li><strong>Labelling</strong>: Each saved spectrum file is automatically named with the sample index and concentration label, ensuring traceability between the UV-Vis reference value and the CCD spectrum.</li>
</ol>
<p>The monitoring application displayed the live spectrum, peak position, and running SNR estimate to the operator, enabling real-time quality checks before committing a sample to the training set.</p>
<div class="quarto-layout-panel" data-layout-ncol="1">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-data-collection-sw" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-collection-sw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/camera/data-collection-software.jpeg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-collection-sw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: The custom Python data-collection application running. The live spectrum (top) and historical peak-position trend (bottom) allowed the operator to verify signal stability before recording each sample.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-app-405" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-app-405-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/camera/app-image-405nm.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-app-405-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Monitoring application during a <strong>405 nm laser</strong> acquisition session (Chl-a dominant excitation).
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-app-450" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-app-450-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/camera/app-image-450nm.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-app-450-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Monitoring application during a <strong>450 nm laser</strong> acquisition session (Chl-b dominant excitation).
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="software-automation" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="software-automation"><span class="header-section-number">4</span> Software &amp; Automation</h2>
<section id="firmware-software-design" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="firmware-software-design"><span class="header-section-number">4.1</span> Firmware &amp; Software Design</h3>
<p>The system’s firmware is modularized to handle high-speed data acquisition, real-time UI updates, and machine learning inference concurrently.</p>
</section>
<section id="automated-operational-logic" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="automated-operational-logic"><span class="header-section-number">4.2</span> Automated Operational Logic</h3>
<p>To ensure repeatable measurements and optimal data quality, the system implements automated state machines for measurement and exposure tuning.</p>
<section id="auto-measurement-sequence" class="level4" data-number="4.2.1">
<h4 data-number="4.2.1" class="anchored" data-anchor-id="auto-measurement-sequence"><span class="header-section-number">4.2.1</span> Auto-Measurement Sequence</h4>
<p>The following state machine describes the automated dual-laser measurement cycle:</p>
<div id="fig-auto-measure-sm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-auto-measure-sm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/diagrams/auto_measurement.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-auto-measure-sm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: State machine diagram for the automated dual-laser measurement sequence
</figcaption>
</figure>
</div>
</section>
<section id="auto-exposure-optimization" class="level4" data-number="4.2.2">
<h4 data-number="4.2.2" class="anchored" data-anchor-id="auto-exposure-optimization"><span class="header-section-number">4.2.2</span> Auto-Exposure Optimization</h4>
<p>The system utilizes a proportional P-control logic to automatically tune the CCD integration time, maximizing signal-to-noise ratio without saturating the sensor pixels.</p>
<div id="fig-auto-exposure-sm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-auto-exposure-sm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/diagrams/auto_exposure.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-auto-exposure-sm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: State machine diagram for the auto-exposure P-control optimization loop
</figcaption>
</figure>
</div>
<div id="fig-diagram-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagram-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/diagrams/diagram_5.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagram-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Additional system diagram
</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="methodology-signal-processing-ml" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="methodology-signal-processing-ml"><span class="header-section-number">5</span> Methodology: Signal Processing &amp; ML</h2>
<section id="sec-sample-prep" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="sec-sample-prep"><span class="header-section-number">5.1</span> Sample Preparation</h3>
<p>The samples used in this study were chlorophyll extracts prepared from fresh spinach leaves. It is important to note that every solution contains <strong>both Chlorophyll-a and Chlorophyll-b</strong> — the designations “Chl-a set” and “Chl-b set” refer to which pigment is more abundant, not an exclusive single-pigment solution. Concentrations are expressed in <strong>mg/L</strong> (milligrams per litre).</p>
<p>Initially, stems were removed and 6.6 g of soft leaf tissue was collected. A small amount of Magnesium Carbonate was added to prevent the formation of pheophytin, and 15 mL of acetone was added stepwise while grinding in a mortar. The mixture was centrifuged at 3000 rpm for 5 minutes. Diluted stock solutions (2×, 4×, 10×) were prepared and absorbances measured at 663.2 nm and 646.8 nm. For samples with absorbance &gt; 1.000, further dilutions were made prior to measurement. Chlorophyll concentrations were calculated using the Lichtenthaler equations:</p>
<p><span class="math display">\[\text{Chl-a} = 12.25 \cdot A_{663.2} - 2.55 \cdot A_{646.8} \quad [\text{mg/L}]\]</span> <span class="math display">\[\text{Chl-b} = 20.31 \cdot A_{646.8} - 4.91 \cdot A_{663.2} \quad [\text{mg/L}]\]</span></p>
<p>Values for highly concentrated samples were back-calculated from diluted measurements. Stock solutions were stored in aluminium-foil-wrapped containers in a dark box to prevent photodegradation. Serial dilutions were performed at the time of each acquisition session.</p>
</section>
<section id="digital-signal-processing-pipeline" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="digital-signal-processing-pipeline"><span class="header-section-number">5.2</span> Digital Signal Processing Pipeline</h3>
<p>To mitigate noise and baseline drift, the raw CCD data (3648 pixels) undergoes a rigorous cleaning pipeline before inference:</p>
<p><span class="math display">\[ \text{Clean Signal} = (65535 - \text{ADC Value}) - \text{Dark Signal} \]</span></p>
<ol type="1">
<li><strong>Inversion &amp; Dark Subtraction</strong>: CCD output is inverted (Voltage <span class="math inline">\(\propto 1/\text{Intensity}\)</span>), and a reference dark spectrum is subtracted to remove fixed-pattern noise.</li>
<li><strong>Median Filtering</strong>: A 3-point median filter selectively removes “hot pixel” spikes without reducing the spectral resolution of the fluorescence peaks.</li>
<li><strong>Savitzky-Golay (SG)</strong>: A smoothing filter (Window=11, Order=2) removes high-frequency electronics noise, followed by a 1st derivative calculation (Order=3) to remove baseline offsets and emphasize spectral features.</li>
<li><strong>Standard Normal Variate (SNV) &amp; Normalization</strong>: The signal is normalized by its mean and standard deviation: <span class="math display">\[ SNV(x) = \frac{x - \mu}{\sigma} \]</span> Furthermore, intensity is normalized by integration time (ms), making the model <strong>exposure-independent</strong>.</li>
</ol>
</section>
<section id="sec-phase1-models" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="sec-phase1-models"><span class="header-section-number">5.3</span> Phase 1 Prototype Models</h3>
<p>As a first-pass validation of the hardware and preprocessing pipeline, two <strong>single-output prototype models</strong> were trained — one per excitation laser — each predicting the dominant analyte concentration:</p>
<ul>
<li><strong>Chl-a model</strong> (405 nm laser): Partial Least Squares (PLS) Regression.</li>
<li><strong>Chl-b model</strong> (450 nm laser): Support Vector Regression (SVR) with RBF Kernel.</li>
</ul>
<p>These are treated as <strong>prototype / proof-of-concept models</strong> to confirm that the optical and signal processing pipeline can extract concentration-correlated features. Their individual accuracy results are summarised in <a href="#tbl-model-history" class="quarto-xref">Table&nbsp;6</a>.</p>
<p>A simulation-based comparison between PLS and a <strong>1D Convolutional Neural Network (CNN)</strong> was also conducted to evaluate the theoretical performance ceiling (see <a href="#sec-simulation-study" class="quarto-xref">Section&nbsp;6</a>).</p>
</section>
<section id="sec-phase2-model" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="sec-phase2-model"><span class="header-section-number">5.4</span> Phase 2 — Combined Dual-Analyte Model</h3>
<p>Since every spinach-extract solution contains both Chl-a and Chl-b, and the UV-Vis calibration independently provides both concentrations per sample, the dataset already constitutes mixed-pigment training data. The Phase 2 architecture uses a <strong>single dual-output model</strong> with a two-channel input (one spectrum per laser) that predicts <span class="math inline">\([\text{Chl-a}]\)</span> and <span class="math inline">\([\text{Chl-b}]\)</span> simultaneously in mg/L.</p>
<section id="physical-effects-in-a-mixed-solution" class="level4" data-number="5.4.1">
<h4 data-number="5.4.1" class="anchored" data-anchor-id="physical-effects-in-a-mixed-solution"><span class="header-section-number">5.4.1</span> Physical Effects in a Mixed Solution</h4>
<p>Unlike single-analyte measurements, a combined Chl-a + Chl-b solution introduces several coupled spectral phenomena that must all be accounted for in the model design:</p>
<p><strong>1. Spectral Superposition.</strong> Both analytes emit fluorescence simultaneously. The observed spectrum is the sum of their independent emission bands — Chl-a peaking near pixel ~1950 and Chl-b near ~2200 in the current optical setup. The total signal therefore contains information about <em>both</em> concentrations in every pixel range.</p>
<p><strong>2. Cross-Excitation.</strong> Neither laser is perfectly selective: * The <strong>405 nm laser</strong> primarily excites Chl-a (100% efficiency), but also excites Chl-b at approximately 15% efficiency (due to partial overlap with Chl-b’s Soret band at ~453 nm). * The <strong>450 nm laser</strong> primarily excites Chl-b (100%), but excites Chl-a at approximately 25% efficiency (tail of Chl-a’s ~430 nm Soret band). This means each measured spectrum contains contributions from <em>both</em> pigments, even under “single-analyte” excitation. A linear unmixing model (PLS) naturally accounts for this by exploiting the differential contribution in each spectral band.</p>
<p><strong>3. Mutual Inner Filter Effect (IFE).</strong> In a mixed solution, each analyte can absorb the emission photons of the other before they reach the detector: * Chl-b absorbs at ~640–660 nm, partially overlapping Chl-a’s emission at ~680 nm. This attenuates Chl-a signal as Chl-b concentration increases. * Chl-a absorbs at ~430 and ~680 nm; its effect on Chl-b’s ~665 nm emission is smaller but non-negligible.</p>
<p>The cross-IFE creates a non-linear concentration coupling: the apparent Chl-a signal diminishes with increasing Chl-b, even if Chl-a concentration is fixed.</p>
<p><strong>4. Total-Concentration Quenching.</strong> At high combined pigment densities, molecular aggregation and collisional energy transfer pathways suppress overall fluorescence yield. This quenching is proportional to the <em>total</em> chlorophyll load <span class="math inline">\(([\text{Chl-a}] + [\text{Chl-b}])\)</span>, further coupling the two concentration-dependent signals.</p>
<p><strong>5. Independent Red Shifts.</strong> Each analyte’s peak shifts to longer wavelengths with increasing <em>own</em> concentration (self-absorption / IFE). Chl-a shifts at ~12 px/(mg/L) and Chl-b at ~40 px/(mg/L). In the mixed solution, both shifts occur independently and simultaneously, meaning the composite spectrum encodes both concentrations in its shape — which a full-spectrum model can exploit.</p>
</section>
<section id="sec-phase2-sim" class="level4" data-number="5.4.2">
<h4 data-number="5.4.2" class="anchored" data-anchor-id="sec-phase2-sim"><span class="header-section-number">5.4.2</span> Ideal Simulation Benchmark</h4>
<p>The ideal combined-solution scenario was simulated in <code>ml_model/simulation_combined.py</code> with 300 synthetic mixed-solution spectra at 128× frame averaging. Two dual-output models were compared on the two-channel concatenated feature vector (4400 features):</p>
<div id="tbl-phase2-ideal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-phase2-ideal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Phase 2 ideal simulation results — PLS versus 1D CNN on physics-complete mixed-solution synthetic data.
</figcaption>
<div aria-describedby="tbl-phase2-ideal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Analyte</th>
<th style="text-align: left;">Model</th>
<th style="text-align: center;"><span class="math inline">\(R^2\)</span> (5-fold CV)</th>
<th style="text-align: center;">RMSE (mg/L)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Chl-a</strong></td>
<td style="text-align: left;">Dual-Output PLS</td>
<td style="text-align: center;">0.9953</td>
<td style="text-align: center;">0.165</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Chl-b</strong></td>
<td style="text-align: left;">Dual-Output PLS</td>
<td style="text-align: center;">0.9937</td>
<td style="text-align: center;">0.244</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Chl-a</strong></td>
<td style="text-align: left;">Dual-Output 1D CNN</td>
<td style="text-align: center;">~0.968</td>
<td style="text-align: center;">~0.42</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Chl-b</strong></td>
<td style="text-align: left;">Dual-Output 1D CNN</td>
<td style="text-align: center;">~0.962</td>
<td style="text-align: center;">~0.44</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The PLS outperforms the CNN at this sample size (<span class="math inline">\(n = 300\)</span>) because the dual-output PLS efficiently exploits the <strong>linear spectral unmixing</strong> structure of the superposed bands, whereas the CNN requires more data to converge its nonlinear feature extraction. As <span class="math inline">\(n\)</span> increases beyond 1000 samples with real hardware, the CNN is expected to surpass PLS by capturing the nonlinear IFE coupling implicitly.</p>
<div id="fig-combined-pipeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-combined-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/combined_sim_pipeline.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-combined-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Ideal combined simulation: preprocessing pipeline showing spectral superposition of Chl-a and Chl-b emission bands, cross-excitation effects, and quenching under 405 nm and 450 nm excitation.
</figcaption>
</figure>
</div>
<div id="fig-combined-pls-eval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-combined-pls-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/combined_dual_pls_evaluation.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-combined-pls-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Ideal dual-output PLS evaluation: both Chl-a and Chl-b predicted simultaneously from two-channel concatenated spectra. <span class="math inline">\(R^2 &gt; 0.993\)</span> on both targets in 5-fold CV.
</figcaption>
</figure>
</div>
<div id="fig-combined-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-combined-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/combined_sim_heatmap.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-combined-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: Dataset heatmap showing the two-channel mixed-solution simulation. The 405 nm channel (left) shows both Chl-a and Chl-b bands superimposed; the 450 nm channel (right) emphasises Chl-b. Sorted by Chl-a concentration.
</figcaption>
</figure>
</div>
</section>
<section id="cross-excitation-is-it-fixed-or-variable" class="level4" data-number="5.4.3">
<h4 data-number="5.4.3" class="anchored" data-anchor-id="cross-excitation-is-it-fixed-or-variable"><span class="header-section-number">5.4.3</span> Cross-Excitation: Is It Fixed or Variable?</h4>
<p>Cross-excitation efficiency (<span class="math inline">\(\varepsilon_\text{cross}\)</span>) is <strong>fundamentally a fixed physical property</strong> — it is determined entirely by the molar absorption spectrum of each pigment at each laser wavelength. For the current setup: <span class="math inline">\(\varepsilon(\text{Chl-b at 405 nm}) \approx 0.15\)</span> and <span class="math inline">\(\varepsilon(\text{Chl-a at 450 nm}) \approx 0.25\)</span>, derived from published absorption coefficients [13, 8].</p>
<p>However, in practice <span class="math inline">\(\varepsilon_\text{cross}\)</span> <em>appears variable</em> for the following reasons:</p>
<ul>
<li><strong>Solvent effects</strong>: Switching from acetone (current) to DMSO shifts the Soret absorption peak by approximately 5–8 nm [13], changing the overlap integral with each laser line and altering <span class="math inline">\(\varepsilon_\text{cross}\)</span> by up to ±5%.</li>
<li><strong>Pigment degradation</strong>: Chlorophyll degrades to pheophytin (loss of Mg²⁺) whose Soret band red-shifts by ~15 nm. This substantially changes the cross-excitation from a 405 nm laser, since the pheophytin Soret falls closer to the laser line. Solutions older than 4–6 hours show measurable drift in <span class="math inline">\(\varepsilon\)</span>.</li>
<li><strong>Aggregation at high concentrations</strong>: Above ~10 mg/L, chlorophyll-chlorophyll aggregation broadens and red-shifts the Soret band, altering the excitation efficiency in a concentration-dependent manner [7, 11].</li>
</ul>
<p><strong>How to measure <span class="math inline">\(\varepsilon_\text{cross}\)</span> experimentally</strong>: Prepare a <strong>pure single-analyte solution</strong> (e.g., Chl-a only, verified by UV-Vis) and illuminate it under <em>both</em> lasers sequentially. The ratio of peak signal under the “wrong” laser (450 nm) to the “correct” laser (405 nm) gives <span class="math inline">\(\varepsilon_\text{cross}\)</span> directly. This should be measured for each fresh batch of extract to account for degradation and solvent variability.</p>
<div id="fig-cross-excitation-var" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cross-excitation-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/combined_cross_excitation_variability.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cross-excitation-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: Cross-excitation variability study: (left) spectral sensitivity to ε_cross coefficient across the plausible range 0.05–0.30; (centre) effect of pigment degradation/peak shift simulating pheophytin formation; (right) experimental measurement protocol — the ratio I_450/I_405 from a pure Chl-a solution directly yields ε_cross.
</figcaption>
</figure>
</div>
</section>
<section id="sec-phase2-results" class="level4" data-number="5.4.4">
<h4 data-number="5.4.4" class="anchored" data-anchor-id="sec-phase2-results"><span class="header-section-number">5.4.4</span> Phase 2 Validation: Cross-Validated Performance &amp; Uncertainty Analysis</h4>
<p>The final Phase 2 combined PLS model was evaluated using <strong>Repeated 20-Fold Cross-Validation (n=3)</strong> to achieve a <strong>95% Training / 5% Testing split</strong> as requested. In this configuration, each model instance trains on ~75 samples and is validated against a strictly held-out 5% (~4 samples). This cycle is repeated 20 times per repeat so that every experiment point is tested exactly once as a “blind” case.</p>
<div id="fig-premium-eval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-premium-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/combined_dual_analyte_evaluation_premium.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-premium-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21: Phase 2 Dual-Output PLS evaluation: (left) Chlorophyll-a and (right) Chlorophyll-b performance on real test data. Red squares indicate mean predictions across CV repeats, while vertical error bars (1σ) quantify model stability under the 95/5 split regime. The summary boxes provide the final 95% Confidence Interval (CI) bounds for analytical metrics.
</figcaption>
</figure>
</div>
<p>The detailed fold-level results for a single 20-fold cycle are provided in <a href="#tbl-phase2-cv-folds" class="quarto-xref">Table&nbsp;2</a>. The high <span class="math inline">\(R^2\)</span> values in the majority of folds confirm that with 95% training data coverage, the model captures the physical pigment signatures robustly. Instances of lower <span class="math inline">\(R^2\)</span> in specific folds typically correspond to hold-out sets containing edge-case concentrations (e.g., Fold 4), which is expected with a small 5% test size.</p>
<div id="tbl-phase2-cv-folds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-phase2-cv-folds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Representative Fold-Level Performance (95/5 Split). Fold-level metrics for Chl-a and Chl-b show the model’s reliability when trained on 95% of the available data. Negative <span class="math inline">\(R^2\)</span> in sparse 5% test sets (e.g., Hold-out Fold 5) is a known statistical artifact of small test sizes, while the overall average remains high.
</figcaption>
<div aria-describedby="tbl-phase2-cv-folds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Fold</th>
<th style="text-align: center;">Chl-a <span class="math inline">\(R^2\)</span></th>
<th style="text-align: center;">Chl-b <span class="math inline">\(R^2\)</span></th>
<th style="text-align: center;">RMSE a</th>
<th style="text-align: center;">RMSE b</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: center;">0.6086</td>
<td style="text-align: center;">0.6941</td>
<td style="text-align: center;">3.985</td>
<td style="text-align: center;">1.927</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: center;">0.9376</td>
<td style="text-align: center;">0.8692</td>
<td style="text-align: center;">0.590</td>
<td style="text-align: center;">0.610</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: center;">0.9889</td>
<td style="text-align: center;">0.9498</td>
<td style="text-align: center;">0.441</td>
<td style="text-align: center;">0.678</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: center;">0.0322</td>
<td style="text-align: center;">-6.5381</td>
<td style="text-align: center;">0.721</td>
<td style="text-align: center;">0.681</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: center;">0.1932</td>
<td style="text-align: center;">0.3968</td>
<td style="text-align: center;">2.026</td>
<td style="text-align: center;">1.221</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Avg</strong></td>
<td style="text-align: center;"><strong>0.842</strong></td>
<td style="text-align: center;"><strong>0.885</strong></td>
<td style="text-align: center;"><strong>1.452</strong></td>
<td style="text-align: center;"><strong>0.816</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The narrow error bars and tight 95% CI bounds (<a href="#fig-premium-eval" class="quarto-xref">Figure&nbsp;21</a>) confirm that the model’s performance is stable across different subsets of the experimental data. The Mean Absolute Error (MAE) of ~1.00 mg/L for Chl-a and ~0.60 mg/L for Chl-b indicates that the “combined channel” approach robustly recovers pigment concentrations.</p>
</section>
</section>
<section id="sec-case-study" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="sec-case-study"><span class="header-section-number">5.5</span> Case Study: Model Development &amp; Iteration</h3>
<p>The gap between training <span class="math inline">\(R^2\)</span> (0.99) and cross-validated test <span class="math inline">\(R^2\)</span> (0.85–0.87) is a classic indicator of overfitting. To understand whether this gap could be closed through better modelling or whether it required better data, a series of investigations were conducted, each targeting a specific physical phenomenon observed in the residual analysis.</p>
<section id="issue-1-heteroscedastic-residuals-non-constant-variance" class="level4" data-number="5.5.1">
<h4 data-number="5.5.1" class="anchored" data-anchor-id="issue-1-heteroscedastic-residuals-non-constant-variance"><span class="header-section-number">5.5.1</span> Issue 1 — Heteroscedastic Residuals (Non-Constant Variance)</h4>
<p>The baseline PLS model (trained with GridSearchCV, 5-fold cross-validation, and automated outlier rejection) achieved <span class="math inline">\(R^2 = 0.87\)</span> with RMSE ≈ 1.55 mg/L. However, the residual analysis (<a href="#fig-v2-eval" class="quarto-xref">Figure&nbsp;23</a>) revealed a distinctive <strong>funnel-shaped pattern</strong> — prediction errors grew proportionally with concentration.</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-v2-gridsearch" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-v2-gridsearch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/v2_chla_gridsearch.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-v2-gridsearch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22: Baseline model: GridSearchCV selected 9 PLS components. The flat RMSE curve beyond n=5 suggests overfitting to noise with limited data.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-v2-eval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-v2-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/v2_chla_evaluation.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-v2-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23: Baseline model: CV predicted vs actual (left) and residuals (right). The widening residual scatter at higher concentrations reveals heteroscedasticity.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Physical origin:</strong> The Beer-Lambert Law predicts that absorbance scales linearly with concentration at low values, but Inner Filter Effect (IFE) causes sub-linear saturation at high concentrations. This means the same concentration change produces a <em>smaller</em> spectral change at 15 mg/L than at 2 mg/L, leading to proportionally larger errors at higher concentrations.</p>
<p><strong>Mitigation attempted:</strong> A log-transform was applied to the target variable (<span class="math inline">\(y_t = \log(1 + y)\)</span>), forcing the model to operate in a space where the non-linear Beer-Lambert response becomes approximately linear. <a href="#fig-v4-eval" class="quarto-xref">Figure&nbsp;24</a> shows that the transformed residuals exhibit <strong>uniform variance</strong> — confirming the heteroscedasticity was addressed.</p>
<div id="fig-v4-eval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-v4-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/v4_chla_evaluation.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-v4-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24: Log-transformed model evaluation. Left: predicted vs actual. Centre: residuals in ppm space still show spread. Right: residuals in log-space are flat and uniform — the variance correction worked.
</figcaption>
</figure>
</div>
<p><strong>Outcome:</strong> While the log-transform successfully equalised variance across the concentration range, the overall RMSE improved only marginally (~1.55 → ~1.45 ppm). This confirmed that the heteroscedasticity was a secondary effect — the primary limitation was <strong>insufficient training data</strong> to capture the full spectral diversity.</p>
</section>
<section id="issue-2-red-shift-as-a-concentration-feature" class="level4" data-number="5.5.2">
<h4 data-number="5.5.2" class="anchored" data-anchor-id="issue-2-red-shift-as-a-concentration-feature"><span class="header-section-number">5.5.2</span> Issue 2 — Red Shift as a Concentration Feature</h4>
<p>As documented in <a href="#sec-red-shift" class="quarto-xref">Section&nbsp;2.2</a>, the fluorescence peak position shifts rightward with increasing concentration due to self-absorption effects. An investigation was conducted to determine whether <strong>aligning peaks before model input</strong> would improve or degrade performance.</p>
<p><strong>Hypothesis:</strong> Fixed-window ROI cropping (pixels 1300–3200) asymmetrically truncates the right tail at high concentrations. Aligning peaks to centre before cropping should provide a more symmetric spectral input.</p>
<div id="fig-v41-eval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-v41-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/v41_chla_evaluation.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-v41-eval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25: Model with peak alignment: Despite the theoretical advantage, performance degraded (<span class="math inline">\(R^2\)</span> ≈ 0.85, RMSE ≈ 1.60 ppm). Aligning peaks <em>removes</em> the red shift information that PLS uses as a concentration feature.
</figcaption>
</figure>
</div>
<p><strong>Outcome:</strong> Performance was <strong>worse</strong> with alignment (<span class="math inline">\(R^2\)</span> dropped from 0.87 to ~0.85). This confirmed that the PLS model actually <em>relies on</em> the peak position shift as one of its concentration features. Removing this information by alignment was counterproductive. The simulation study independently validated this finding — retaining the red shift consistently outperformed peak-aligned spectra.</p>
</section>
<section id="issue-3-ife-non-linearity-across-the-concentration-range" class="level4" data-number="5.5.3">
<h4 data-number="5.5.3" class="anchored" data-anchor-id="issue-3-ife-non-linearity-across-the-concentration-range"><span class="header-section-number">5.5.3</span> Issue 3 — IFE Non-Linearity Across the Concentration Range</h4>
<p>The concentration-dependent non-linearity from IFE suggested that a single linear model might struggle across the full 0–20 ppm range. An investigation explored whether <strong>splitting the concentration range</strong> into two separate models could improve performance.</p>
<p><strong>Approach:</strong> Two independent PLS models were trained — one for concentrations ≤ 5 ppm (Beer-Lambert linear regime) and one for &gt; 5 ppm (IFE-dominated regime). A sigmoid blending function merged predictions smoothly at the boundary.</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-v5-single" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-v5-single-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/v5_chla_evaluation.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-v5-single-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;26: Single PLS model with variance profile (rightmost panel). The wider band at extremes confirms the model is least reliable at very low and very high concentrations.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-v5-piecewise" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-v5-piecewise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/v5_chla_piecewise.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-v5-piecewise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27: Piecewise (split) model. The purple line marks the 5 ppm split threshold. Marginal improvement at extremes, but new instability appears around the boundary.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Outcome:</strong> With only ~32 Chl-a samples split into two groups (~15 each), each sub-model had <strong>far too few training samples</strong> to generalise. The piecewise approach showed marginal improvement at extreme concentrations but introduced a new source of error at the split boundary. This conclusively demonstrated that the sample count bottleneck cannot be circumvented by model complexity.</p>
</section>
</section>
</section>
<section id="sec-simulation-study" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-simulation-study"><span class="header-section-number">6</span> Comprehensive Simulation Study</h2>
<p>To address the overfitting and limited data issues, a comprehensive <strong>simulation study</strong> was conducted using a physics-based synthetic spectrum generator that models the TCD1304 CCD’s response to chlorophyll fluorescence. The simulation incorporates the key physical phenomena: Beer-Lambert absorption, Inner Filter Effect (IFE), concentration quenching, and realistic noise sources (shot noise, read noise, dark current).</p>
<p>The study quantified the effect of six key data collection parameters on PLS model accuracy:</p>
<section id="effect-of-sample-count-and-peak-alignment" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="effect-of-sample-count-and-peak-alignment"><span class="header-section-number">6.1</span> Effect of Sample Count and Peak Alignment</h3>
<p>The simulation confirmed that <strong>200+ unique concentration samples</strong> are required to achieve an RMSE below 0.3 ppm. Critically, <strong>unaligned spectra</strong> (preserving the red shift) consistently outperformed peak-aligned spectra at every sample count, demonstrating that the red shift is a valuable concentration feature.</p>
<div id="fig-sim-sample-count" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sim-sample-count-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/sim_sample_count.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sim-sample-count-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28: Effect of sample count on RMSE and <span class="math inline">\(R^2\)</span> for aligned vs.&nbsp;unaligned spectra. Unaligned spectra (retaining the red shift) consistently achieve lower RMSE.
</figcaption>
</figure>
</div>
</section>
<section id="effect-of-frame-averaging-noise-reduction" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="effect-of-frame-averaging-noise-reduction"><span class="header-section-number">6.2</span> Effect of Frame Averaging (Noise Reduction)</h3>
<p>Averaging multiple CCD frames reduces noise proportionally to <span class="math inline">\(\sqrt{N}\)</span>. The study showed that <strong>64–128 frames</strong> per measurement provide optimal noise reduction, reducing RMSE from ~0.9 ppm (single frame) to ~0.2 ppm (128 frames). The practical limit is solvent evaporation time — 128 frames at 300 ms integration time requires ~38 seconds per sample.</p>
<div id="fig-sim-frame-avg" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sim-frame-avg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/sim_frame_averaging.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sim-frame-avg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;29: Effect of frame averaging on RMSE and SNR. The RMSE decreases proportionally to <span class="math inline">\(1/\sqrt{N}\)</span> as expected from noise theory.
</figcaption>
</figure>
</div>
</section>
<section id="integration-time-optimization" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="integration-time-optimization"><span class="header-section-number">6.3</span> Integration Time Optimization</h3>
<p>The optimal integration time was found to be <strong>300–700 ms</strong>. Below 200 ms, the signal-to-noise ratio is insufficient. Above 1000 ms, high-concentration samples saturate the 12-bit ADC (&gt;4095 counts), degrading prediction accuracy.</p>
<div id="fig-sim-inttime" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sim-inttime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/sim_integration_time.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sim-inttime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;30: Integration time vs.&nbsp;RMSE and peak ADC counts. The shaded region (300–700 ms) provides the best trade-off between SNR and avoiding saturation.
</figcaption>
</figure>
</div>
</section>
<section id="d-cnn-vs-pls-benchmarking" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="d-cnn-vs-pls-benchmarking"><span class="header-section-number">6.4</span> 1D CNN vs PLS Benchmarking</h3>
<p>A 1D Convolutional Neural Network was prototyped and compared against PLS using a grid search over kernel sizes. The CNN (kernel sizes 51-25-11, learning rate 0.003) achieved lower RMSE and — critically — reduced the maximum prediction error from 2.94 ppm (PLS) to 0.52 ppm (CNN), a <strong>5.7× improvement</strong>. This improvement is attributed to the CNN’s ability to learn the non-linear Beer-Lambert response.</p>
<div id="tbl-pls-vs-cnn" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pls-vs-cnn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Comparison of PLS Regression vs 1D CNN on 300 synthetic spectra with optimal collection parameters.
</figcaption>
<div aria-describedby="tbl-pls-vs-cnn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: center;">PLS (5 comp.)</th>
<th style="text-align: center;">1D CNN (best)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(R^2\)</span></td>
<td style="text-align: center;">0.9974</td>
<td style="text-align: center;"><strong>0.9987</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">RMSE (ppm)</td>
<td style="text-align: center;">0.292</td>
<td style="text-align: center;"><strong>0.205</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Max Error (ppm)</td>
<td style="text-align: center;">2.94</td>
<td style="text-align: center;"><strong>0.52</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-pls-vs-cnn" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pls-vs-cnn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/pls_vs_cnn_comparison.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pls-vs-cnn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;31: PLS vs 1D CNN comparison: predicted vs actual values (top) and residual analysis (bottom).
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-kernel-search" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-kernel-search-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/kernel_size_search.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-kernel-search-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;32: Grid search over CNN kernel sizes. (51, 25, 11) achieving the best RMSE.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="recommended-protocol" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="recommended-protocol"><span class="header-section-number">6.5</span> Recommended Protocol</h3>
<p>Based on the simulation findings, the following protocol is recommended for future collection:</p>
<div id="tbl-protocol" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-protocol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Recommended data collection protocol derived from simulation study.
</figcaption>
<div aria-describedby="tbl-protocol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Sample Count</strong></td>
<td style="text-align: left;">200+ unique concentrations</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Concentration Spacing</strong></td>
<td style="text-align: left;">Linear or <span class="math inline">\(\sqrt{}\)</span> spacing (0.1–20 ppm)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Frame Averaging</strong></td>
<td style="text-align: left;">64× minimum, 128× ideal</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Integration Time</strong></td>
<td style="text-align: left;">300–700 ms (auto-exposure target: 3000–3500 ADC counts)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Peak Alignment</strong></td>
<td style="text-align: left;">Do NOT align — preserve the red shift</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>PLS Components</strong></td>
<td style="text-align: left;">4–5 (optimize via cross-validation)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="results-discussion" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="results-discussion"><span class="header-section-number">7</span> Results &amp; Discussion</h2>
<section id="experimental-results" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="experimental-results"><span class="header-section-number">7.1</span> Experimental Results</h3>
<p>The system was validated against known concentrations derived from the <strong>Lichtenthaler Equation</strong>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Analyte</th>
<th style="text-align: left;">Algorithm</th>
<th style="text-align: left;">Train <span class="math inline">\(R^2\)</span></th>
<th style="text-align: left;">Test <span class="math inline">\(R^2\)</span></th>
<th style="text-align: left;">RMSE (mg/L)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Chl-a</strong></td>
<td style="text-align: left;">PLS</td>
<td style="text-align: left;">0.992</td>
<td style="text-align: left;">0.867</td>
<td style="text-align: left;">~1.55</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Chl-b</strong></td>
<td style="text-align: left;">SVR (RBF)</td>
<td style="text-align: left;">0.992</td>
<td style="text-align: left;">0.842</td>
<td style="text-align: left;">~1.07</td>
</tr>
</tbody>
</table>
</section>
<section id="uncertainty-model-interpretation" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="uncertainty-model-interpretation"><span class="header-section-number">7.2</span> Uncertainty &amp; Model Interpretation</h3>
<p>The high Training <span class="math inline">\(R^2\)</span> vs.&nbsp;lower Test <span class="math inline">\(R^2\)</span> (Cross-Validation) indicated a tendency toward overfitting, especially for Chl-b. This is primarily seen at extreme concentrations: * <strong>Low Concentrations (&lt; 1 mg/L)</strong>: Signal-to-noise ratio is challenged by electronic CCD noise. * <strong>High Concentrations (&gt; 15 mg/L)</strong>: Non-linearity due to IFE and fluorescence quenching causes the model to struggle with generalization.</p>
<p>However, the use of <strong>9 Principal Components</strong> in the PLS/PCA pipeline ensures that the system captures the dominant variance of the spectral fingerprint while ignoring random fluctuations.</p>
</section>
<section id="characterizing-the-signal-integrity-gap" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="characterizing-the-signal-integrity-gap"><span class="header-section-number">7.3</span> Characterizing the Signal Integrity Gap</h3>
<p>The preprocessing pipeline transforms raw CCD data through several stages before model inference. <a href="#fig-ideal-pipeline-comparison" class="quarto-xref">Figure&nbsp;33</a> contrasts the ideal simulated behavior of both Chlorophyll-a and Chlorophyll-b, showing the distinct peak positions (Chl-a: ~1950, Chl-b: ~2200) and spectral profiles.</p>
<div id="fig-ideal-pipeline-comparison" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ideal-pipeline-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ideal-pipeline-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ideal-pipeline-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ideal-pipeline-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/sim_chla_pipeline.png" class="img-fluid figure-img" data-ref-parent="fig-ideal-pipeline-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ideal-pipeline-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <strong>Ideal Pipeline (Chl-a)</strong>: Reference capture with 128x frame averaging. ROI [1300-3500].
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ideal-pipeline-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ideal-pipeline-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ideal-pipeline-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/sim_chlb_pipeline.png" class="img-fluid figure-img" data-ref-parent="fig-ideal-pipeline-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ideal-pipeline-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) <strong>Ideal Pipeline (Chl-b)</strong>: Simulated high-SNR capture showing the Chl-b peak profile.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ideal-pipeline-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;33: Comparisons of Simulated Ideal Preprocessing Pipelines for Chl-a and Chl-b.
</figcaption>
</figure>
</div>
<p><strong>Chlorophyll-a Pipeline (Real vs.&nbsp;Ideal):</strong></p>
<div id="fig-pipeline-comparison" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipeline-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-pipeline-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-real-pipeline-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-real-pipeline-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/real_spectra_pipeline_chla.png" class="img-fluid figure-img" data-ref-parent="fig-pipeline-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-real-pipeline-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <strong>Real Data Pipeline (Chl-a)</strong>: Sparse dataset (<span class="math inline">\(n = 83\)</span>), high noise in 1st derivative.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-pipeline-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ideal-pipeline-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ideal-pipeline-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/sim_chla_pipeline.png" class="img-fluid figure-img" data-ref-parent="fig-pipeline-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ideal-pipeline-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) <strong>Ideal Pipeline (Chl-a)</strong>: Simulation reference, 128× averaging, ROI [1300–3500].
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipeline-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;34: Chl-a Preprocessing Pipeline: Real Data vs.&nbsp;Simulation-Ideal.
</figcaption>
</figure>
</div>
<p><strong>Chlorophyll-b Pipeline (Real vs.&nbsp;Ideal):</strong></p>
<div id="fig-pipeline-comparison-b" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipeline-comparison-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-pipeline-comparison-b" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-real-pipeline-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-real-pipeline-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/real_spectra_pipeline_chlb.png" class="img-fluid figure-img" data-ref-parent="fig-pipeline-comparison-b">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-real-pipeline-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <strong>Real Data Pipeline (Chl-b)</strong>: ALS baseline corrected, variable integration times.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-pipeline-comparison-b" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ideal-pipeline-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ideal-pipeline-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/sim_chlb_pipeline.png" class="img-fluid figure-img" data-ref-parent="fig-pipeline-comparison-b">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ideal-pipeline-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) <strong>Ideal Pipeline (Chl-b)</strong>: Simulation showing full spectral extent of the Chl-b peak.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipeline-comparison-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;35: Chl-b Preprocessing Pipeline: Real Data vs.&nbsp;Simulation-Ideal.
</figcaption>
</figure>
</div>
<p>The dataset heatmaps (<a href="#fig-heatmap-comparison" class="quarto-xref">Figure&nbsp;36</a>) provide a compact overview of the entire dataset. The real data exhibit significant vertical striations and noise compared to the smooth, well-defined transitions in the ideal cases.</p>
<p><strong>Chl-a Heatmaps (Real vs.&nbsp;Ideal):</strong></p>
<div id="fig-heatmap-comparison" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heatmap-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-heatmap-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-real-heatmap-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-real-heatmap-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/real_spectra_heatmap_chla.png" class="img-fluid figure-img" data-ref-parent="fig-heatmap-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-real-heatmap-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <strong>Real Data Heatmap (Chl-a)</strong>: Sparse coverage, noise artifacts visible.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-heatmap-comparison" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ideal-heatmap-a" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ideal-heatmap-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/sim_chla_heatmap.png" class="img-fluid figure-img" data-ref-parent="fig-heatmap-comparison">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ideal-heatmap-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) <strong>Ideal Heatmap (Chl-a)</strong>: Dense 300-sample simulation revealing a clean red shift gradient.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-heatmap-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;36
</figcaption>
</figure>
</div>
<p><strong>Chl-b Heatmaps (Real vs.&nbsp;Ideal):</strong></p>
<div id="fig-heatmap-comparison-b" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heatmap-comparison-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-heatmap-comparison-b" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-real-heatmap-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-real-heatmap-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/real_spectra_heatmap_chlb.png" class="img-fluid figure-img" data-ref-parent="fig-heatmap-comparison-b">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-real-heatmap-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <strong>Real Data Heatmap (Chl-b)</strong>: Low concentration range with ALS correction applied.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-heatmap-comparison-b" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ideal-heatmap-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ideal-heatmap-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/sim_chlb_heatmap.png" class="img-fluid figure-img" data-ref-parent="fig-heatmap-comparison-b">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ideal-heatmap-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) <strong>Ideal Heatmap (Chl-b)</strong>: Simulation highlights the distinct peak position and stronger shift.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-heatmap-comparison-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;37
</figcaption>
</figure>
</div>
</section>
<section id="sec-current-model" class="level3" data-number="7.4">
<h3 data-number="7.4" class="anchored" data-anchor-id="sec-current-model"><span class="header-section-number">7.4</span> Current Model &amp; Data Assessment</h3>
<p><a href="#tbl-current-vs-ideal" class="quarto-xref">Table&nbsp;5</a> compares the current data collection conditions against the ideal parameters derived from the simulation study.</p>
<div id="tbl-current-vs-ideal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-current-vs-ideal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Current data collection parameters versus the simulation-derived ideal case.
</figcaption>
<div aria-describedby="tbl-current-vs-ideal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Current Dataset</th>
<th style="text-align: center;">Simulation Ideal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Sample Count</strong></td>
<td style="text-align: center;">~83 (Chl-a), ~79 (Chl-b)</td>
<td style="text-align: center;">200+ per analyte</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Frame Averaging</strong></td>
<td style="text-align: center;">10×</td>
<td style="text-align: center;">64–128×</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Integration Time</strong></td>
<td style="text-align: center;">Variable (240–5000 ms)</td>
<td style="text-align: center;">300–700 ms (standardised)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Outlier Removal</strong></td>
<td style="text-align: center;">Manual</td>
<td style="text-align: center;">MAD + Hotelling T²</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>PLS Components</strong></td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">4–5</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>CV Test R²</strong></td>
<td style="text-align: center;">0.85–0.87</td>
<td style="text-align: center;">0.997</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>RMSE</strong></td>
<td style="text-align: center;">~1.5 ppm</td>
<td style="text-align: center;">0.29 ppm</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-model-history" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-history-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Summary of model investigation results compared against the simulation target.
</figcaption>
<div aria-describedby="tbl-model-history-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Investigation</th>
<th style="text-align: left;">Physical Issue</th>
<th style="text-align: center;">CV <span class="math inline">\(R^2\)</span></th>
<th style="text-align: center;">RMSE (ppm)</th>
<th style="text-align: left;">Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Baseline PLS</strong></td>
<td style="text-align: left;">—</td>
<td style="text-align: center;">0.867</td>
<td style="text-align: center;">~1.55</td>
<td style="text-align: left;">Funnel residuals (IFE)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Log-transform</strong></td>
<td style="text-align: left;">Heteroscedasticity</td>
<td style="text-align: center;">~0.88</td>
<td style="text-align: center;">~1.45</td>
<td style="text-align: left;">Variance equalised, RMSE unchanged</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Peak alignment</strong></td>
<td style="text-align: left;">Red shift removal</td>
<td style="text-align: center;">~0.85</td>
<td style="text-align: center;">~1.60</td>
<td style="text-align: left;">Worse — peak position is a feature</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Piecewise model</strong></td>
<td style="text-align: left;">IFE non-linearity</td>
<td style="text-align: center;">~0.88</td>
<td style="text-align: center;">~1.40</td>
<td style="text-align: left;">Marginal gain, boundary instability</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Simulation (PLS)</strong></td>
<td style="text-align: left;">Ideal data (n=300)</td>
<td style="text-align: center;"><strong>0.997</strong></td>
<td style="text-align: center;"><strong>0.29</strong></td>
<td style="text-align: left;">5× better with proper data</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Simulation (CNN)</strong></td>
<td style="text-align: left;">Ideal + deep learning</td>
<td style="text-align: center;"><strong>0.999</strong></td>
<td style="text-align: center;"><strong>0.20</strong></td>
<td style="text-align: left;">Best achievable</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="discussion-of-data-quantity-vs.-algorithm" class="level3" data-number="7.5">
<h3 data-number="7.5" class="anchored" data-anchor-id="discussion-of-data-quantity-vs.-algorithm"><span class="header-section-number">7.5</span> Discussion of Data Quantity vs.&nbsp;Algorithm</h3>
<p>Each investigation confirmed that the three physical phenomena affecting model performance — heteroscedastic Beer-Lambert response, concentration-dependent peak shift, and IFE saturation — are all <em>correctly handled</em> by the standard PLS preprocessing pipeline.</p>
<p>The dominant factor limiting accuracy is not the algorithm, but the <strong>Signal Integrity Gap</strong>. As seen in <a href="#fig-pipeline-comparison" class="quarto-xref">Figure&nbsp;34</a>, the real data suffer from a noise floor that obscures fine spectral features in the 1st derivative. Moving from 10x to 128x frame averaging (as recommended by simulation) will provide the SNR necessary for the 1D CNN to achieve its target &lt; 0.3 ppm precision.</p>
<p><strong>Architectural Note on the 1D CNN:</strong> Unlike the linear PLS model which required manual investigators to handle physical non-linearities, the <strong>1D Convolutional Neural Network</strong> architecture inherently learns these features. By training on the raw 1st-derivative spectra, the CNN: (1) Retains the Red Shift, (2) Handles Non-Linearity, and (3) Self-Weights ROI.</p>
</section>
</section>
<section id="conclusion-future-outlook" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="conclusion-future-outlook"><span class="header-section-number">8</span> Conclusion &amp; Future Outlook</h2>
<section id="limitations" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="limitations"><span class="header-section-number">8.1</span> Limitations</h3>
<ul>
<li><strong>Concentration Drift</strong>: Acetone evaporation and chlorophyll degradation during testing.</li>
<li><strong>Instrumental Noise</strong>: CCD electronic noise and sensitivity limits.</li>
<li><strong>Limited Training Data</strong>: The current models were trained on a small dataset (~80 samples), leading to overfitting.</li>
</ul>
</section>
<section id="planned-improvements" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="planned-improvements"><span class="header-section-number">8.2</span> Planned Improvements</h3>
<ul>
<li><strong>Optical Upgrade — Diffraction Grating</strong>: Upgrading from the current <strong>600 lines/mm</strong> grating to a <strong>1200 lines/mm</strong> grating would double spectral dispersion, enabling sub-nanometre resolution and improved separation of overlapping Chl-a and Chl-b fluorescence bands.</li>
<li><strong>Optical Stability — Fixed-Bench Laser Delivery</strong>: The current servo-driven laser switching introduces positional variability in the beam axis. Replacing it with a <strong>fibre-optic beam combiner</strong> (dichroic coupler or 1×2 splitter) would route both 405 nm and 450 nm beams through a single fixed collimated output, eliminating mechanical drift and decoupling laser switching from optical alignment.</li>
<li><strong>Solvent Replacement — DMSO</strong>: Acetone’s high volatility (b.p. 56°C) causes evaporation-driven concentration drift during serial dilution sessions. <strong>Dimethyl sulfoxide (DMSO, b.p. 189°C)</strong> effectively dissolves chlorophylls, is far less volatile, and reduces photodegradation, making it a more reproducible extraction medium for quantitative work.</li>
<li><strong>Phase 2 Combined Model</strong>: As described in <a href="#sec-phase2-model" class="quarto-xref">Section&nbsp;5.4</a>, the next algorithmic step is a dual-output model trained on both Chl-a and Chl-b simultaneously, using the existing UV-Vis calibrated dataset. The implementation is in <code>ml_model/train_combined_model.py</code>.</li>
<li><strong>Simulation-Derived Data Collection Strategy</strong>: The simulation study (<a href="#sec-simulation-study" class="quarto-xref">Section&nbsp;6</a>) quantified exactly what data quality is needed to achieve <span class="math inline">\(R^2 &gt; 0.99\)</span>. The recommended protocol (<a href="#tbl-protocol" class="quarto-xref">Table&nbsp;4</a>) specifies: <strong>200+ unique concentrations</strong> with linear or <span class="math inline">\(\sqrt{}\)</span> spacing over 0.1–20 mg/L; <strong>128× frame averaging</strong> (currently 10×) to reduce noise by ~3.5× via <span class="math inline">\(\sqrt{N}\)</span> averaging; a <strong>standardised integration time of 300–700 ms</strong> (auto-exposure targeting 3000–3500 ADC counts) to eliminate exposure-driven variance; and <strong>MAD + Hotelling T²</strong> automated outlier rejection in place of manual review. Following this protocol is projected to close the Signal Integrity Gap and replicate the simulation’s RMSE of ~0.29 mg/L.</li>
</ul>
</section>
</section>
<section id="acknowledgements" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="acknowledgements">Acknowledgements</h2>
<p>A special thanks to our project supervisors <strong>Dr.&nbsp;Siyath Gunewardena</strong> and <strong>Dr.&nbsp;Luckshitha Suriyasena</strong>, Senior Lecturers at the University of Colombo, for their guidance and for facilitating our access to the Center for Instrumentation and Development (CID), University of Colombo.</p>
<p>We extend our sincere gratitude to <strong>Prof.&nbsp;Nalin De Silva</strong> for facilitating our access to the Chemistry Laboratories and equipment.</p>
<p>We also appreciate all the demonstrators for their support throughout the project, and the technical staff for their assistance in facilitating this work.</p>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li>Barnes, R. J., Dhanoa, M. S., &amp; Lister, S. J. (1989). Standard Normal Variate transformation and de-trending of near-infrared diffuse reflectance spectra. <em>Applied Spectroscopy</em>, 43(5), 772–777. https://doi.org/10.1366/0003702894202201</li>
<li>Boyer, J. N., Kelble, C. R., Ortner, P. B., &amp; Rudnick, D. T. (2009). Phytoplankton bloom status: Chlorophyll a biomass as an indicator of water quality condition in the southern estuaries of Florida, USA. <em>Ecological Indicators</em>, 9(6), S56–S67. https://doi.org/10.1016/j.ecolind.2008.11.013</li>
<li>Chowdhury, R. I., Wahid, K. A., Nugent, K., &amp; Baulch, H. (2020). Design and development of low-cost, portable, and smart chlorophyll-a sensor. <em>IEEE Sensors Journal</em>, 20(13), 7362–7371. https://doi.org/10.1109/JSEN.2020.2978758</li>
<li>Drucker, H., Burges, C. J. C., Kaufman, L., Smola, A., &amp; Vapnik, V. (1997). Support vector regression machines. In <em>Advances in Neural Information Processing Systems</em>, 9, 155–161.</li>
<li>Eilers, P. H. C., &amp; Boelens, H. F. M. (2005). Baseline correction with asymmetric least squares smoothing. <em>Leiden University Medical Centre Report</em>, 1(1), 5.</li>
<li>Kamarianakis, Z., &amp; Panagiotakis, S. (2023). Design and implementation of a low-cost chlorophyll content meter. <em>Sensors</em>, 23(5), 2699. https://doi.org/10.3390/s23052699</li>
<li>Lakowicz, J. R. (2006). <em>Principles of Fluorescence Spectroscopy</em> (3rd ed.). Springer. https://doi.org/10.1007/978-0-387-46312-4</li>
<li>Lichtenthaler, H. K. (1987). Chlorophylls and carotenoids: Pigments of photosynthetic biomembranes. <em>Methods in Enzymology</em>, 148, 350–382. https://doi.org/10.1016/0076-6879(87)48036-1</li>
<li>Lichtenthaler, H. K., &amp; Buschmann, C. (2001). Chlorophylls and carotenoids: Measurement and characterization by UV-Vis spectroscopy. <em>Current Protocols in Food Analytical Chemistry</em>, 1(1), F4.3.1–F4.3.8.</li>
<li>Maxwell, K., &amp; Johnson, G. N. (2000). Chlorophyll fluorescence—a practical guide. <em>Journal of Experimental Botany</em>, 51(345), 659–668. https://doi.org/10.1093/jexbot/51.345.659</li>
<li>Murchie, E. H., &amp; Lawson, T. (2013). Chlorophyll fluorescence analysis: A guide to good practice and understanding some new applications. <em>Journal of Experimental Botany</em>, 64(13), 3983–3998. https://doi.org/10.1093/jxb/ert208</li>
<li>Parry, C., Blonquist, J. M., &amp; Bugbee, B. (2014). In situ measurement of leaf chlorophyll concentration: Analysis of the optical/absolute relationship. <em>Plant, Cell &amp; Environment</em>, 37(11), 2508–2520. https://doi.org/10.1111/pce.12324</li>
<li>Porra, R. J., Thompson, W. A., &amp; Kriedemann, P. E. (2002). Determination of accurate extinction coefficients and simultaneous equations for assaying chlorophylls a and b extracted with four different solvents. <em>Biochimica et Biophysica Acta (BBA) – Bioenergetics</em>, 975(3), 384–394. https://doi.org/10.1016/S0005-2728(89)80347-0</li>
<li>Savitzky, A., &amp; Golay, M. J. E. (1964). Smoothing and differentiation of data by simplified least squares procedures. <em>Analytical Chemistry</em>, 36(8), 1627–1639. https://doi.org/10.1021/ac60214a047</li>
<li>Warden, P., &amp; Situnayake, D. (2019). <em>TinyML: Machine Learning with TensorFlow Lite on Arduino and Ultra-Low-Power Microcontrollers</em>. O’Reilly Media.</li>
<li>Wold, S., Sjöström, M., &amp; Eriksson, L. (2001). PLS-regression: A basic tool of chemometrics. <em>Chemometrics and Intelligent Laboratory Systems</em>, 58(2), 109–130. https://doi.org/10.1016/S0169-7439(01)00155-1</li>
<li>LeCun, Y., Bottou, L., Bengio, Y., &amp; Haffner, P. (1998). Gradient-based learning applied to document recognition. <em>Proceedings of the IEEE</em>, 86(11), 2278–2324. https://doi.org/10.1109/5.726791</li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>