"""
Export the saved PLS model from chla2_pls_model.pkl to C header files
for STM32H7 embedded deployment.

Uses the ORIGINAL preprocessing parameters:
  - SG smoothing: window_length=11, polyorder=2
  - SG 1st derivative: window_length=11, polyorder=3
  - SNV normalization

Model: PLSRegression with 20 components, 3694 features, scale=True
"""

import numpy as np
import joblib
from pathlib import Path
from scipy.signal import savgol_coeffs

# ============================================================
# PATHS
# ============================================================
MODEL_PATH = Path(r"C:\Users\user\Downloads\data files of project\chla2\pls\chla2_pls_model.pkl")
OUTPUT_DIR = Path(r"C:\Users\user\Downloads\data files of project\chla2\New folder")

# Preprocessing parameters (from chla2_pls_model.py)
SG_WINDOW = 11
SG_POLY_SMOOTH = 2
SG_POLY_DERIV = 3

# ============================================================
# LOAD MODEL
# ============================================================
print("Loading model...")
data = joblib.load(MODEL_PATH)
model = data['model']
n_components = int(data['n_components'])
feature_count = int(data['feature_count'])

print(f"  Model: PLSRegression")
print(f"  Components: {n_components}")
print(f"  Features: {feature_count}")
print(f"  Intercept: {model.intercept_[0]:.10f}")

# Extract scaling parameters (PLS with scale=True)
x_mean = model._x_mean.astype(np.float32)
x_std = model._x_std.astype(np.float32)
coef = model.coef_.ravel().astype(np.float32)
intercept = float(model.intercept_[0])

# Fix any zero stds to avoid division by zero
x_std[x_std == 0] = 1e-8

print(f"  x_mean range: [{x_mean.min():.6f}, {x_mean.max():.6f}]")
print(f"  x_std range:  [{x_std.min():.6f}, {x_std.max():.6f}]")
print(f"  coef range:   [{coef.min():.6f}, {coef.max():.6f}]")

# ============================================================
# COMPUTE SG FILTER COEFFICIENTS
# ============================================================
print("\nComputing SG filter coefficients...")

# Smoothing coefficients (deriv=0)
sg_smooth_coeffs = savgol_coeffs(SG_WINDOW, SG_POLY_SMOOTH, deriv=0).astype(np.float32)
print(f"  Smooth coeffs ({SG_WINDOW}): {sg_smooth_coeffs}")

# 1st derivative coefficients (deriv=1)
sg_deriv_coeffs = savgol_coeffs(SG_WINDOW, SG_POLY_DERIV, deriv=1).astype(np.float32)
print(f"  Deriv coeffs ({SG_WINDOW}):  {sg_deriv_coeffs}")

# ============================================================
# HELPER: Format C array
# ============================================================
def format_c_array(name, arr, dtype="float", per_line=8):
    """Format a numpy array as a C array string."""
    lines = []
    lines.append(f"static const {dtype} {name}[{len(arr)}] = {{")
    for i in range(0, len(arr), per_line):
        chunk = arr[i:i+per_line]
        vals = ", ".join(f"{v:.10e}f" for v in chunk)
        if i + per_line < len(arr):
            vals += ","
        lines.append(f"    {vals}")
    lines.append("};")
    return "\n".join(lines)

# ============================================================
# GENERATE pls_model_data.h
# ============================================================
print("\nGenerating pls_model_data.h ...")

header = f"""/*
 * pls_model_data.h
 * Auto-generated PLS model parameters for STM32H7 deployment
 * 
 * Model: PLSRegression (n_components={n_components}, scale=True)
 * Features: {feature_count}
 * Preprocessing: SG smooth (w={SG_WINDOW}, p={SG_POLY_SMOOTH})
 *                -> SG 1st deriv (w={SG_WINDOW}, p={SG_POLY_DERIV})
 *                -> SNV normalization
 *
 * Generated by export_model_for_stm32.py
 */

#ifndef PLS_MODEL_DATA_H
#define PLS_MODEL_DATA_H

#include <stdint.h>

/* Model dimensions */
#define NUM_FEATURES        {feature_count}
#define NUM_PLS_COMPONENTS  {n_components}

/* Preprocessing parameters */
#define SG_WINDOW_SIZE      {SG_WINDOW}
#define SG_HALF_WINDOW      {SG_WINDOW // 2}
#define SG_POLY_SMOOTH      {SG_POLY_SMOOTH}
#define SG_POLY_DERIV       {SG_POLY_DERIV}

/* PLS intercept (bias) */
#define PLS_INTERCEPT       {intercept:.10e}f

/* Savitzky-Golay smoothing filter coefficients (window={SG_WINDOW}, poly={SG_POLY_SMOOTH}, deriv=0) */
{format_c_array("SG_SMOOTH_COEFFS", sg_smooth_coeffs)}

/* Savitzky-Golay 1st derivative filter coefficients (window={SG_WINDOW}, poly={SG_POLY_DERIV}, deriv=1) */
{format_c_array("SG_DERIV1_COEFFS", sg_deriv_coeffs)}

/* PLS regression coefficients (coef_ from sklearn) */
{format_c_array("PLS_COEF", coef)}

/* Feature means for scaling (x_mean from sklearn PLS) */
{format_c_array("PLS_X_MEAN", x_mean)}

/* Feature standard deviations for scaling (x_std from sklearn PLS) */
{format_c_array("PLS_X_STD", x_std)}

#endif /* PLS_MODEL_DATA_H */
"""

out_path = OUTPUT_DIR / "pls_model_data.h"
with open(out_path, 'w') as f:
    f.write(header)
print(f"  Written: {out_path}")
print(f"  File size: {out_path.stat().st_size / 1024:.1f} KB")

# ============================================================
# VERIFICATION: Python prediction on a test vector
# ============================================================
print("\n--- Verification ---")
# Create a simple test spectrum (zeros preprocessed) to verify C implementation
test_input = np.random.RandomState(42).randn(feature_count).astype(np.float32) * 0.01
test_scaled = (test_input - x_mean) / x_std
test_pred = float(np.dot(test_scaled, coef) + intercept)
print(f"  Test input (first 5): {test_input[:5]}")
print(f"  Python prediction: {test_pred:.10f}")
print(f"  (Use this to verify C implementation)")

# Save test vector for C verification
test_header = f"""/*
 * test_vector.h
 * Test vector for verifying C PLS implementation matches Python
 */

#ifndef TEST_VECTOR_H
#define TEST_VECTOR_H

#define TEST_EXPECTED_PREDICTION  {test_pred:.10e}f

/* Test input spectrum (already preprocessed, {feature_count} values) */
{format_c_array("TEST_INPUT", test_input)}

#endif /* TEST_VECTOR_H */
"""

test_path = OUTPUT_DIR / "test_vector.h"
with open(test_path, 'w') as f:
    f.write(test_header)
print(f"  Test vector written: {test_path}")

print("\n✅ Export complete!")
